# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Rubyterm.destroy_all


Rubyterm.create(:rubyterm => '=== (SystemCallError)
')
Rubyterm.create(:rubyterm => '::DEBUG (Thread)
')
Rubyterm.create(:rubyterm => '::DEBUG= (Thread)
')
Rubyterm.create(:rubyterm => '::[] (Array)
')
Rubyterm.create(:rubyterm => '::[] (Dir)
')
Rubyterm.create(:rubyterm => '::[] (ENV)
')
Rubyterm.create(:rubyterm => '::[] (Hash)
')
Rubyterm.create(:rubyterm => '::[]= (ENV)
')
Rubyterm.create(:rubyterm => '::_id2ref (ObjectSpace)
')
Rubyterm.create(:rubyterm => '::_load (Time)
')
Rubyterm.create(:rubyterm => '::abort (Process)
')
Rubyterm.create(:rubyterm => '::abort_on_exception (Thread)
')
Rubyterm.create(:rubyterm => '::abort_on_exception= (Thread)
')
Rubyterm.create(:rubyterm => '::absolute_path (File)
')
Rubyterm.create(:rubyterm => '::acos (Math)
')
Rubyterm.create(:rubyterm => '::acosh (Math)
')
Rubyterm.create(:rubyterm => '::aliases (Encoding)
')
Rubyterm.create(:rubyterm => '::all_symbols (Symbol)
')
Rubyterm.create(:rubyterm => '::asciicompat_encoding (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '::asin (Math)
')
Rubyterm.create(:rubyterm => '::asinh (Math)
')
Rubyterm.create(:rubyterm => '::assoc (ENV)
')
Rubyterm.create(:rubyterm => '::at (Time)
')
Rubyterm.create(:rubyterm => '::atan (Math)
')
Rubyterm.create(:rubyterm => '::atan2 (Math)
')
Rubyterm.create(:rubyterm => '::atanh (Math)
')
Rubyterm.create(:rubyterm => '::atime (File)
')
Rubyterm.create(:rubyterm => '::basename (File)
')
Rubyterm.create(:rubyterm => '::binread (IO)
')
Rubyterm.create(:rubyterm => '::binwrite (IO)
')
Rubyterm.create(:rubyterm => '::blockdev? (File)
')
Rubyterm.create(:rubyterm => '::cbrt (Math)
')
Rubyterm.create(:rubyterm => '::change_privilege (Process::GID)
')
Rubyterm.create(:rubyterm => '::change_privilege (Process::UID)
')
Rubyterm.create(:rubyterm => '::chardev? (File)
')
Rubyterm.create(:rubyterm => '::chdir (Dir)
')
Rubyterm.create(:rubyterm => '::chmod (File)
')
Rubyterm.create(:rubyterm => '::chown (File)
')
Rubyterm.create(:rubyterm => '::chroot (Dir)
')
Rubyterm.create(:rubyterm => '::clear (ENV)
')
Rubyterm.create(:rubyterm => '::clear (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::compatible? (Encoding)
')
Rubyterm.create(:rubyterm => '::compile (Regexp)
')
Rubyterm.create(:rubyterm => '::compile (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::compile_file (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::compile_option (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::compile_option= (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::constants (Module)
')
Rubyterm.create(:rubyterm => '::copy_stream (IO)
')
Rubyterm.create(:rubyterm => '::cos (Math)
')
Rubyterm.create(:rubyterm => '::cosh (Math)
')
Rubyterm.create(:rubyterm => '::count (GC)
')
Rubyterm.create(:rubyterm => '::count_objects (ObjectSpace)
')
Rubyterm.create(:rubyterm => '::ctime (File)
')
Rubyterm.create(:rubyterm => '::current (Fiber)
')
Rubyterm.create(:rubyterm => '::current (Thread)
')
Rubyterm.create(:rubyterm => '::daemon (Process)
')
Rubyterm.create(:rubyterm => '::default_external (Encoding)
')
Rubyterm.create(:rubyterm => '::default_external= (Encoding)
')
Rubyterm.create(:rubyterm => '::default_internal (Encoding)
')
Rubyterm.create(:rubyterm => '::default_internal= (Encoding)
')
Rubyterm.create(:rubyterm => '::define_finalizer (ObjectSpace)
')
Rubyterm.create(:rubyterm => '::delete (Dir)
')
Rubyterm.create(:rubyterm => '::delete (ENV)
')
Rubyterm.create(:rubyterm => '::delete (File)
')
Rubyterm.create(:rubyterm => '::delete_if (ENV)
')
Rubyterm.create(:rubyterm => '::detach (Process)
')
Rubyterm.create(:rubyterm => '::directory? (File)
')
Rubyterm.create(:rubyterm => '::dirname (File)
')
Rubyterm.create(:rubyterm => '::disable (GC)
')
Rubyterm.create(:rubyterm => '::disable (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::disasm (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::disassemble (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::dump (Marshal)
')
Rubyterm.create(:rubyterm => '::each (ENV)
')
Rubyterm.create(:rubyterm => '::each_key (ENV)
')
Rubyterm.create(:rubyterm => '::each_object (ObjectSpace)
')
Rubyterm.create(:rubyterm => '::each_pair (ENV)
')
Rubyterm.create(:rubyterm => '::each_value (ENV)
')
Rubyterm.create(:rubyterm => '::egid (Process)
')
Rubyterm.create(:rubyterm => '::egid= (Process)
')
Rubyterm.create(:rubyterm => '::eid (Process::GID)
')
Rubyterm.create(:rubyterm => '::eid (Process::UID)
')
Rubyterm.create(:rubyterm => '::empty? (ENV)
')
Rubyterm.create(:rubyterm => '::enable (GC)
')
Rubyterm.create(:rubyterm => '::enable (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::enabled? (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::entries (Dir)
')
Rubyterm.create(:rubyterm => '::erf (Math)
')
Rubyterm.create(:rubyterm => '::erfc (Math)
')
Rubyterm.create(:rubyterm => '::escape (Regexp)
')
Rubyterm.create(:rubyterm => '::euid (Process)
')
Rubyterm.create(:rubyterm => '::euid= (Process)
')
Rubyterm.create(:rubyterm => '::exception (Exception)
')
Rubyterm.create(:rubyterm => '::exclusive (Thread)
')
Rubyterm.create(:rubyterm => '::exec (Process)
')
Rubyterm.create(:rubyterm => '::executable? (File)
')
Rubyterm.create(:rubyterm => '::executable_real? (File)
')
Rubyterm.create(:rubyterm => '::exist? (Dir)
')
Rubyterm.create(:rubyterm => '::exist? (File)
')
Rubyterm.create(:rubyterm => '::exists? (Dir)
')
Rubyterm.create(:rubyterm => '::exists? (File)
')
Rubyterm.create(:rubyterm => '::exit (Process)
')
Rubyterm.create(:rubyterm => '::exit (Thread)
')
Rubyterm.create(:rubyterm => '::exit! (Process)
')
Rubyterm.create(:rubyterm => '::exp (Math)
')
Rubyterm.create(:rubyterm => '::expand_path (File)
')
Rubyterm.create(:rubyterm => '::extname (File)
')
Rubyterm.create(:rubyterm => '::fetch (ENV)
')
Rubyterm.create(:rubyterm => '::file? (File)
')
Rubyterm.create(:rubyterm => '::find (Encoding)
')
Rubyterm.create(:rubyterm => '::fnmatch (File)
')
Rubyterm.create(:rubyterm => '::fnmatch? (File)
')
Rubyterm.create(:rubyterm => '::for_fd (IO)
')
Rubyterm.create(:rubyterm => '::foreach (Dir)
')
Rubyterm.create(:rubyterm => '::foreach (IO)
')
Rubyterm.create(:rubyterm => '::fork (Process)
')
Rubyterm.create(:rubyterm => '::fork (Thread)
')
Rubyterm.create(:rubyterm => '::frexp (Math)
')
Rubyterm.create(:rubyterm => '::ftype (File)
')
Rubyterm.create(:rubyterm => '::gamma (Math)
')
Rubyterm.create(:rubyterm => '::garbage_collect (ObjectSpace)
')
Rubyterm.create(:rubyterm => '::getegid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::geteuid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::getgid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::getpgid (Process)
')
Rubyterm.create(:rubyterm => '::getpgrp (Process)
')
Rubyterm.create(:rubyterm => '::getpriority (Process)
')
Rubyterm.create(:rubyterm => '::getrlimit (Process)
')
Rubyterm.create(:rubyterm => '::getuid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::getwd (Dir)
')
Rubyterm.create(:rubyterm => '::gid (Process)
')
Rubyterm.create(:rubyterm => '::gid= (Process)
')
Rubyterm.create(:rubyterm => '::glob (Dir)
')
Rubyterm.create(:rubyterm => '::gm (Time)
')
Rubyterm.create(:rubyterm => '::grant_privilege (Process::GID)
')
Rubyterm.create(:rubyterm => '::grant_privilege (Process::UID)
')
Rubyterm.create(:rubyterm => '::groups (Process)
')
Rubyterm.create(:rubyterm => '::groups= (Process)
')
Rubyterm.create(:rubyterm => '::grpowned? (File)
')
Rubyterm.create(:rubyterm => '::has_key? (ENV)
')
Rubyterm.create(:rubyterm => '::has_value? (ENV)
')
Rubyterm.create(:rubyterm => '::home (Dir)
')
Rubyterm.create(:rubyterm => '::hypot (Math)
')
Rubyterm.create(:rubyterm => '::identical? (File)
')
Rubyterm.create(:rubyterm => '::include? (ENV)
')
Rubyterm.create(:rubyterm => '::index (ENV)
')
Rubyterm.create(:rubyterm => '::initgroups (Process)
')
Rubyterm.create(:rubyterm => '::inspect (ENV)
')
Rubyterm.create(:rubyterm => '::invert (ENV)
')
Rubyterm.create(:rubyterm => '::issetugid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::join (File)
')
Rubyterm.create(:rubyterm => '::keep_if (ENV)
')
Rubyterm.create(:rubyterm => '::key (ENV)
')
Rubyterm.create(:rubyterm => '::key? (ENV)
')
Rubyterm.create(:rubyterm => '::keys (ENV)
')
Rubyterm.create(:rubyterm => '::kill (Process)
')
Rubyterm.create(:rubyterm => '::kill (Thread)
')
Rubyterm.create(:rubyterm => '::last_match (Regexp)
')
Rubyterm.create(:rubyterm => '::lchmod (File)
')
Rubyterm.create(:rubyterm => '::lchown (File)
')
Rubyterm.create(:rubyterm => '::ldexp (Math)
')
Rubyterm.create(:rubyterm => '::length (ENV)
')
Rubyterm.create(:rubyterm => '::lgamma (Math)
')
Rubyterm.create(:rubyterm => '::link (File)
')
Rubyterm.create(:rubyterm => '::list (Encoding)
')
Rubyterm.create(:rubyterm => '::list (Signal)
')
Rubyterm.create(:rubyterm => '::list (Thread)
')
Rubyterm.create(:rubyterm => '::load (Marshal)
')
Rubyterm.create(:rubyterm => '::load (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::local (Time)
')
Rubyterm.create(:rubyterm => '::locale_charmap (Encoding)
')
Rubyterm.create(:rubyterm => '::log (Math)
')
Rubyterm.create(:rubyterm => '::log10 (Math)
')
Rubyterm.create(:rubyterm => '::log2 (Math)
')
Rubyterm.create(:rubyterm => '::lstat (File)
')
Rubyterm.create(:rubyterm => '::main (Thread)
')
Rubyterm.create(:rubyterm => '::malloc_allocated_size (GC)
')
Rubyterm.create(:rubyterm => '::malloc_allocations (GC)
')
Rubyterm.create(:rubyterm => '::maxgroups (Process)
')
Rubyterm.create(:rubyterm => '::maxgroups= (Process)
')
Rubyterm.create(:rubyterm => '::member? (ENV)
')
Rubyterm.create(:rubyterm => '::mkdir (Dir)
')
Rubyterm.create(:rubyterm => '::mktime (Time)
')
Rubyterm.create(:rubyterm => '::mtime (File)
')
Rubyterm.create(:rubyterm => '::name_list (Encoding)
')
Rubyterm.create(:rubyterm => '::nesting (Module)
')
Rubyterm.create(:rubyterm => '::new (Array)
')
Rubyterm.create(:rubyterm => '::new (BasicObject)
')
Rubyterm.create(:rubyterm => '::new (Class)
')
Rubyterm.create(:rubyterm => '::new (Dir)
')
Rubyterm.create(:rubyterm => '::new (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '::new (Enumerator)
')
Rubyterm.create(:rubyterm => '::new (Exception)
')
Rubyterm.create(:rubyterm => '::new (File)
')
Rubyterm.create(:rubyterm => '::new (File::Stat)
')
Rubyterm.create(:rubyterm => '::new (Hash)
')
Rubyterm.create(:rubyterm => '::new (IO)
')
Rubyterm.create(:rubyterm => '::new (Module)
')
Rubyterm.create(:rubyterm => '::new (Mutex)
')
Rubyterm.create(:rubyterm => '::new (NameError)
')
Rubyterm.create(:rubyterm => '::new (NoMethodError)
')
Rubyterm.create(:rubyterm => '::new (Proc)
')
Rubyterm.create(:rubyterm => '::new (Random)
')
Rubyterm.create(:rubyterm => '::new (Range)
')
Rubyterm.create(:rubyterm => '::new (Regexp)
')
Rubyterm.create(:rubyterm => '::new (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '::new (SignalException)
')
Rubyterm.create(:rubyterm => '::new (String)
')
Rubyterm.create(:rubyterm => '::new (Struct)
')
Rubyterm.create(:rubyterm => '::new (SystemCallError)
')
Rubyterm.create(:rubyterm => '::new (SystemExit)
')
Rubyterm.create(:rubyterm => '::new (Time)
')
Rubyterm.create(:rubyterm => '::new_seed (Random)
')
Rubyterm.create(:rubyterm => '::now (Time)
')
Rubyterm.create(:rubyterm => '::open (Dir)
')
Rubyterm.create(:rubyterm => '::open (File)
')
Rubyterm.create(:rubyterm => '::open (IO)
')
Rubyterm.create(:rubyterm => '::owned? (File)
')
Rubyterm.create(:rubyterm => '::pass (Thread)
')
Rubyterm.create(:rubyterm => '::path (File)
')
Rubyterm.create(:rubyterm => '::pid (Process)
')
Rubyterm.create(:rubyterm => '::pipe (IO)
')
Rubyterm.create(:rubyterm => '::pipe? (File)
')
Rubyterm.create(:rubyterm => '::polar (Complex)
')
Rubyterm.create(:rubyterm => '::popen (IO)
')
Rubyterm.create(:rubyterm => '::ppid (Process)
')
Rubyterm.create(:rubyterm => '::pwd (Dir)
')
Rubyterm.create(:rubyterm => '::quote (Regexp)
')
Rubyterm.create(:rubyterm => '::rand (Random)
')
Rubyterm.create(:rubyterm => '::rassoc (ENV)
')
Rubyterm.create(:rubyterm => '::re_exchange (Process::GID)
')
Rubyterm.create(:rubyterm => '::re_exchange (Process::UID)
')
Rubyterm.create(:rubyterm => '::re_exchangeable? (Process::GID)
')
Rubyterm.create(:rubyterm => '::re_exchangeable? (Process::UID)
')
Rubyterm.create(:rubyterm => '::read (IO)
')
Rubyterm.create(:rubyterm => '::readable? (File)
')
Rubyterm.create(:rubyterm => '::readable_real? (File)
')
Rubyterm.create(:rubyterm => '::readlines (IO)
')
Rubyterm.create(:rubyterm => '::readlink (File)
')
Rubyterm.create(:rubyterm => '::realdirpath (File)
')
Rubyterm.create(:rubyterm => '::realpath (File)
')
Rubyterm.create(:rubyterm => '::rect (Complex)
')
Rubyterm.create(:rubyterm => '::rectangular (Complex)
')
Rubyterm.create(:rubyterm => '::rehash (ENV)
')
Rubyterm.create(:rubyterm => '::reject (ENV)
')
Rubyterm.create(:rubyterm => '::reject! (ENV)
')
Rubyterm.create(:rubyterm => '::rename (File)
')
Rubyterm.create(:rubyterm => '::replace (ENV)
')
Rubyterm.create(:rubyterm => '::report (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::restore (Marshal)
')
Rubyterm.create(:rubyterm => '::result (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::rid (Process::GID)
')
Rubyterm.create(:rubyterm => '::rid (Process::UID)
')
Rubyterm.create(:rubyterm => '::rmdir (Dir)
')
Rubyterm.create(:rubyterm => '::search_convpath (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '::select (ENV)
')
Rubyterm.create(:rubyterm => '::select (IO)
')
Rubyterm.create(:rubyterm => '::select! (ENV)
')
Rubyterm.create(:rubyterm => '::setegid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::seteuid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setgid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setgid? (File)
')
Rubyterm.create(:rubyterm => '::setpgid (Process)
')
Rubyterm.create(:rubyterm => '::setpgrp (Process)
')
Rubyterm.create(:rubyterm => '::setpriority (Process)
')
Rubyterm.create(:rubyterm => '::setregid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setresgid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setresuid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setreuid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setrgid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setrlimit (Process)
')
Rubyterm.create(:rubyterm => '::setruid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setsid (Process)
')
Rubyterm.create(:rubyterm => '::setuid (Process::Sys)
')
Rubyterm.create(:rubyterm => '::setuid? (File)
')
Rubyterm.create(:rubyterm => '::shift (ENV)
')
Rubyterm.create(:rubyterm => '::sid_available? (Process::GID)
')
Rubyterm.create(:rubyterm => '::sid_available? (Process::UID)
')
Rubyterm.create(:rubyterm => '::sin (Math)
')
Rubyterm.create(:rubyterm => '::sinh (Math)
')
Rubyterm.create(:rubyterm => '::size (ENV)
')
Rubyterm.create(:rubyterm => '::size (File)
')
Rubyterm.create(:rubyterm => '::size? (File)
')
Rubyterm.create(:rubyterm => '::socket? (File)
')
Rubyterm.create(:rubyterm => '::spawn (Process)
')
Rubyterm.create(:rubyterm => '::split (File)
')
Rubyterm.create(:rubyterm => '::sqrt (Math)
')
Rubyterm.create(:rubyterm => '::srand (Random)
')
Rubyterm.create(:rubyterm => '::start (GC)
')
Rubyterm.create(:rubyterm => '::start (Thread)
')
Rubyterm.create(:rubyterm => '::stat (File)
')
Rubyterm.create(:rubyterm => '::stat (GC)
')
Rubyterm.create(:rubyterm => '::sticky? (File)
')
Rubyterm.create(:rubyterm => '::stop (Thread)
')
Rubyterm.create(:rubyterm => '::store (ENV)
')
Rubyterm.create(:rubyterm => '::stress (GC)
')
Rubyterm.create(:rubyterm => '::stress= (GC)
')
Rubyterm.create(:rubyterm => '::switch (Process::GID)
')
Rubyterm.create(:rubyterm => '::switch (Process::UID)
')
Rubyterm.create(:rubyterm => '::symlink (File)
')
Rubyterm.create(:rubyterm => '::symlink? (File)
')
Rubyterm.create(:rubyterm => '::sysopen (IO)
')
Rubyterm.create(:rubyterm => '::tan (Math)
')
Rubyterm.create(:rubyterm => '::tanh (Math)
')
Rubyterm.create(:rubyterm => '::times (Process)
')
Rubyterm.create(:rubyterm => '::to_a (ENV)
')
Rubyterm.create(:rubyterm => '::to_hash (ENV)
')
Rubyterm.create(:rubyterm => '::to_s (ENV)
')
Rubyterm.create(:rubyterm => '::total_time (GC::Profiler)
')
Rubyterm.create(:rubyterm => '::trap (Signal)
')
Rubyterm.create(:rubyterm => '::truncate (File)
')
Rubyterm.create(:rubyterm => '::try_convert (Array)
')
Rubyterm.create(:rubyterm => '::try_convert (Hash)
')
Rubyterm.create(:rubyterm => '::try_convert (IO)
')
Rubyterm.create(:rubyterm => '::try_convert (Regexp)
')
Rubyterm.create(:rubyterm => '::try_convert (String)
')
Rubyterm.create(:rubyterm => '::uid (Process)
')
Rubyterm.create(:rubyterm => '::uid= (Process)
')
Rubyterm.create(:rubyterm => '::umask (File)
')
Rubyterm.create(:rubyterm => '::undefine_finalizer (ObjectSpace)
')
Rubyterm.create(:rubyterm => '::union (Regexp)
')
Rubyterm.create(:rubyterm => '::unlink (Dir)
')
Rubyterm.create(:rubyterm => '::unlink (File)
')
Rubyterm.create(:rubyterm => '::update (ENV)
')
Rubyterm.create(:rubyterm => '::utc (Time)
')
Rubyterm.create(:rubyterm => '::utime (File)
')
Rubyterm.create(:rubyterm => '::value? (ENV)
')
Rubyterm.create(:rubyterm => '::values (ENV)
')
Rubyterm.create(:rubyterm => '::values_at (ENV)
')
Rubyterm.create(:rubyterm => '::wait (Process)
')
Rubyterm.create(:rubyterm => '::wait2 (Process)
')
Rubyterm.create(:rubyterm => '::waitall (Process)
')
Rubyterm.create(:rubyterm => '::waitpid (Process)
')
Rubyterm.create(:rubyterm => '::waitpid2 (Process)
')
Rubyterm.create(:rubyterm => '::world_readable? (File)
')
Rubyterm.create(:rubyterm => '::world_writable? (File)
')
Rubyterm.create(:rubyterm => '::writable? (File)
')
Rubyterm.create(:rubyterm => '::writable_real? (File)
')
Rubyterm.create(:rubyterm => '::write (IO)
')
Rubyterm.create(:rubyterm => '::yield (Fiber)
')
Rubyterm.create(:rubyterm => '::zero? (File)
')
Rubyterm.create(:rubyterm => '#! (BasicObject)
')
Rubyterm.create(:rubyterm => '#!= (BasicObject)
')
Rubyterm.create(:rubyterm => '#!~ (Object)
')
Rubyterm.create(:rubyterm => '#% (Bignum)
')
Rubyterm.create(:rubyterm => '#% (Fixnum)
')
Rubyterm.create(:rubyterm => '#% (Float)
')
Rubyterm.create(:rubyterm => '#% (Numeric)
')
Rubyterm.create(:rubyterm => '#% (String)
')
Rubyterm.create(:rubyterm => '#& (Array)
')
Rubyterm.create(:rubyterm => '#& (Bignum)
')
Rubyterm.create(:rubyterm => '#& (FalseClass)
')
Rubyterm.create(:rubyterm => '#& (Fixnum)
')
Rubyterm.create(:rubyterm => '#& (NilClass)
')
Rubyterm.create(:rubyterm => '#& (Process::Status)
')
Rubyterm.create(:rubyterm => '#& (TrueClass)
')
Rubyterm.create(:rubyterm => '#* (Array)
')
Rubyterm.create(:rubyterm => '#* (Bignum)
')
Rubyterm.create(:rubyterm => '#* (Complex)
')
Rubyterm.create(:rubyterm => '#* (Fixnum)
')
Rubyterm.create(:rubyterm => '#* (Float)
')
Rubyterm.create(:rubyterm => '#* (Rational)
')
Rubyterm.create(:rubyterm => '#* (String)
')
Rubyterm.create(:rubyterm => '#** (Bignum)
')
Rubyterm.create(:rubyterm => '#** (Complex)
')
Rubyterm.create(:rubyterm => '#** (Fixnum)
')
Rubyterm.create(:rubyterm => '#** (Float)
')
Rubyterm.create(:rubyterm => '#** (Rational)
')
Rubyterm.create(:rubyterm => '#+ (Array)
')
Rubyterm.create(:rubyterm => '#+ (Bignum)
')
Rubyterm.create(:rubyterm => '#+ (Complex)
')
Rubyterm.create(:rubyterm => '#+ (Fixnum)
')
Rubyterm.create(:rubyterm => '#+ (Float)
')
Rubyterm.create(:rubyterm => '#+ (Rational)
')
Rubyterm.create(:rubyterm => '#+ (String)
')
Rubyterm.create(:rubyterm => '#+ (Time)
')
Rubyterm.create(:rubyterm => '#+@ (Numeric)
')
Rubyterm.create(:rubyterm => '#- (Array)
')
Rubyterm.create(:rubyterm => '#- (Bignum)
')
Rubyterm.create(:rubyterm => '#- (Complex)
')
Rubyterm.create(:rubyterm => '#- (Fixnum)
')
Rubyterm.create(:rubyterm => '#- (Float)
')
Rubyterm.create(:rubyterm => '#- (Rational)
')
Rubyterm.create(:rubyterm => '#- (Time)
')
Rubyterm.create(:rubyterm => '#-@ (Bignum)
')
Rubyterm.create(:rubyterm => '#-@ (Complex)
')
Rubyterm.create(:rubyterm => '#-@ (Fixnum)
')
Rubyterm.create(:rubyterm => '#-@ (Float)
')
Rubyterm.create(:rubyterm => '#-@ (Numeric)
')
Rubyterm.create(:rubyterm => '#/ (Bignum)
')
Rubyterm.create(:rubyterm => '#/ (Complex)
')
Rubyterm.create(:rubyterm => '#/ (Fixnum)
')
Rubyterm.create(:rubyterm => '#/ (Float)
')
Rubyterm.create(:rubyterm => '#/ (Rational)
')
Rubyterm.create(:rubyterm => '#< (Bignum)
')
Rubyterm.create(:rubyterm => '#< (Comparable)
')
Rubyterm.create(:rubyterm => '#< (Fixnum)
')
Rubyterm.create(:rubyterm => '#< (Float)
')
Rubyterm.create(:rubyterm => '#< (Module)
')
Rubyterm.create(:rubyterm => '#<< (Array)
')
Rubyterm.create(:rubyterm => '#<< (Bignum)
')
Rubyterm.create(:rubyterm => '#<< (Fixnum)
')
Rubyterm.create(:rubyterm => '#<< (IO)
')
Rubyterm.create(:rubyterm => '#<< (String)
')
Rubyterm.create(:rubyterm => '#<= (Bignum)
')
Rubyterm.create(:rubyterm => '#<= (Comparable)
')
Rubyterm.create(:rubyterm => '#<= (Fixnum)
')
Rubyterm.create(:rubyterm => '#<= (Float)
')
Rubyterm.create(:rubyterm => '#<= (Module)
')
Rubyterm.create(:rubyterm => '#<=> (Array)
')
Rubyterm.create(:rubyterm => '#<=> (Bignum)
')
Rubyterm.create(:rubyterm => '#<=> (File::Stat)
')
Rubyterm.create(:rubyterm => '#<=> (Fixnum)
')
Rubyterm.create(:rubyterm => '#<=> (Float)
')
Rubyterm.create(:rubyterm => '#<=> (Module)
')
Rubyterm.create(:rubyterm => '#<=> (Numeric)
')
Rubyterm.create(:rubyterm => '#<=> (Object)
')
Rubyterm.create(:rubyterm => '#<=> (Rational)
')
Rubyterm.create(:rubyterm => '#<=> (String)
')
Rubyterm.create(:rubyterm => '#<=> (Symbol)
')
Rubyterm.create(:rubyterm => '#<=> (Time)
')
Rubyterm.create(:rubyterm => '#== (Array)
')
Rubyterm.create(:rubyterm => '#== (BasicObject)
')
Rubyterm.create(:rubyterm => '#== (Bignum)
')
Rubyterm.create(:rubyterm => '#== (Comparable)
')
Rubyterm.create(:rubyterm => '#== (Complex)
')
Rubyterm.create(:rubyterm => '#== (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#== (Exception)
')
Rubyterm.create(:rubyterm => '#== (Fixnum)
')
Rubyterm.create(:rubyterm => '#== (Float)
')
Rubyterm.create(:rubyterm => '#== (Hash)
')
Rubyterm.create(:rubyterm => '#== (MatchData)
')
Rubyterm.create(:rubyterm => '#== (Method)
')
Rubyterm.create(:rubyterm => '#== (Module)
')
Rubyterm.create(:rubyterm => '#== (Proc)
')
Rubyterm.create(:rubyterm => '#== (Process::Status)
')
Rubyterm.create(:rubyterm => '#== (Random)
')
Rubyterm.create(:rubyterm => '#== (Range)
')
Rubyterm.create(:rubyterm => '#== (Rational)
')
Rubyterm.create(:rubyterm => '#== (Regexp)
')
Rubyterm.create(:rubyterm => '#== (String)
')
Rubyterm.create(:rubyterm => '#== (Struct)
')
Rubyterm.create(:rubyterm => '#== (Symbol)
')
Rubyterm.create(:rubyterm => '#== (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#=== (Bignum)
')
Rubyterm.create(:rubyterm => '#=== (Fixnum)
')
Rubyterm.create(:rubyterm => '#=== (Float)
')
Rubyterm.create(:rubyterm => '#=== (Module)
')
Rubyterm.create(:rubyterm => '#=== (Object)
')
Rubyterm.create(:rubyterm => '#=== (Proc)
')
Rubyterm.create(:rubyterm => '#=== (Range)
')
Rubyterm.create(:rubyterm => '#=== (Regexp)
')
Rubyterm.create(:rubyterm => '#=== (String)
')
Rubyterm.create(:rubyterm => '#=== (Symbol)
')
Rubyterm.create(:rubyterm => '#=~ (Object)
')
Rubyterm.create(:rubyterm => '#=~ (Regexp)
')
Rubyterm.create(:rubyterm => '#=~ (String)
')
Rubyterm.create(:rubyterm => '#=~ (Symbol)
')
Rubyterm.create(:rubyterm => '#> (Bignum)
')
Rubyterm.create(:rubyterm => '#> (Comparable)
')
Rubyterm.create(:rubyterm => '#> (Fixnum)
')
Rubyterm.create(:rubyterm => '#> (Float)
')
Rubyterm.create(:rubyterm => '#> (Module)
')
Rubyterm.create(:rubyterm => '#>= (Bignum)
')
Rubyterm.create(:rubyterm => '#>= (Comparable)
')
Rubyterm.create(:rubyterm => '#>= (Fixnum)
')
Rubyterm.create(:rubyterm => '#>= (Float)
')
Rubyterm.create(:rubyterm => '#>= (Module)
')
Rubyterm.create(:rubyterm => '#>> (Bignum)
')
Rubyterm.create(:rubyterm => '#>> (Fixnum)
')
Rubyterm.create(:rubyterm => '#>> (Process::Status)
')
Rubyterm.create(:rubyterm => '#Array (Kernel)
')
Rubyterm.create(:rubyterm => '#Complex (Kernel)
')
Rubyterm.create(:rubyterm => '#Float (Kernel)
')
Rubyterm.create(:rubyterm => '#Integer (Kernel)
')
Rubyterm.create(:rubyterm => '#Rational (Kernel)
')
Rubyterm.create(:rubyterm => '#String (Kernel)
')
Rubyterm.create(:rubyterm => '#[] (Array)
')
Rubyterm.create(:rubyterm => '#[] (Bignum)
')
Rubyterm.create(:rubyterm => '#[] (Continuation)
')
Rubyterm.create(:rubyterm => '#[] (Fixnum)
')
Rubyterm.create(:rubyterm => '#[] (Hash)
')
Rubyterm.create(:rubyterm => '#[] (MatchData)
')
Rubyterm.create(:rubyterm => '#[] (Method)
')
Rubyterm.create(:rubyterm => '#[] (Proc)
')
Rubyterm.create(:rubyterm => '#[] (String)
')
Rubyterm.create(:rubyterm => '#[] (Struct)
')
Rubyterm.create(:rubyterm => '#[] (Symbol)
')
Rubyterm.create(:rubyterm => '#[] (Thread)
')
Rubyterm.create(:rubyterm => '#[]= (Array)
')
Rubyterm.create(:rubyterm => '#[]= (Hash)
')
Rubyterm.create(:rubyterm => '#[]= (String)
')
Rubyterm.create(:rubyterm => '#[]= (Struct)
')
Rubyterm.create(:rubyterm => '#[]= (Thread)
')
Rubyterm.create(:rubyterm => '#^ (Bignum)
')
Rubyterm.create(:rubyterm => '#^ (FalseClass)
')
Rubyterm.create(:rubyterm => '#^ (Fixnum)
')
Rubyterm.create(:rubyterm => '#^ (NilClass)
')
Rubyterm.create(:rubyterm => '#^ (TrueClass)
')
Rubyterm.create(:rubyterm => '#__callee__ (Kernel)
')
Rubyterm.create(:rubyterm => '#__id__ (BasicObject)
')
Rubyterm.create(:rubyterm => '#__method__ (Kernel)
')
Rubyterm.create(:rubyterm => '#__send__ (BasicObject)
')
Rubyterm.create(:rubyterm => '#_dump (Time)
')
Rubyterm.create(:rubyterm => '#` (Kernel)
')
Rubyterm.create(:rubyterm => '#abort (Kernel)
')
Rubyterm.create(:rubyterm => '#abort_on_exception (Thread)
')
Rubyterm.create(:rubyterm => '#abort_on_exception= (Thread)
')
Rubyterm.create(:rubyterm => '#abs (Bignum)
')
Rubyterm.create(:rubyterm => '#abs (Complex)
')
Rubyterm.create(:rubyterm => '#abs (Fixnum)
')
Rubyterm.create(:rubyterm => '#abs (Float)
')
Rubyterm.create(:rubyterm => '#abs (Numeric)
')
Rubyterm.create(:rubyterm => '#abs2 (Complex)
')
Rubyterm.create(:rubyterm => '#abs2 (Numeric)
')
Rubyterm.create(:rubyterm => '#add (ThreadGroup)
')
Rubyterm.create(:rubyterm => '#add_trace_func (Thread)
')
Rubyterm.create(:rubyterm => '#advise (IO)
')
Rubyterm.create(:rubyterm => '#alias_method (Module)
')
Rubyterm.create(:rubyterm => '#alive? (Fiber)
')
Rubyterm.create(:rubyterm => '#alive? (Thread)
')
Rubyterm.create(:rubyterm => '#all? (Enumerable)
')
Rubyterm.create(:rubyterm => '#allocate (Class)
')
Rubyterm.create(:rubyterm => '#ancestors (Module)
')
Rubyterm.create(:rubyterm => '#angle (Complex)
')
Rubyterm.create(:rubyterm => '#angle (Float)
')
Rubyterm.create(:rubyterm => '#angle (Numeric)
')
Rubyterm.create(:rubyterm => '#any? (Enumerable)
')
Rubyterm.create(:rubyterm => '#append_features (Module)
')
Rubyterm.create(:rubyterm => '#arg (Complex)
')
Rubyterm.create(:rubyterm => '#arg (Float)
')
Rubyterm.create(:rubyterm => '#arg (Numeric)
')
Rubyterm.create(:rubyterm => '#args (NoMethodError)
')
Rubyterm.create(:rubyterm => '#argv (ARGF)
')
Rubyterm.create(:rubyterm => '#arity (Method)
')
Rubyterm.create(:rubyterm => '#arity (Proc)
')
Rubyterm.create(:rubyterm => '#arity (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#ascii_compatible? (Encoding)
')
Rubyterm.create(:rubyterm => '#ascii_only? (String)
')
Rubyterm.create(:rubyterm => '#asctime (Time)
')
Rubyterm.create(:rubyterm => '#assoc (Array)
')
Rubyterm.create(:rubyterm => '#assoc (Hash)
')
Rubyterm.create(:rubyterm => '#at (Array)
')
Rubyterm.create(:rubyterm => '#at_exit (Kernel)
')
Rubyterm.create(:rubyterm => '#atime (File)
')
Rubyterm.create(:rubyterm => '#atime (File::Stat)
')
Rubyterm.create(:rubyterm => '#attr (Module)
')
Rubyterm.create(:rubyterm => '#attr_accessor (Module)
')
Rubyterm.create(:rubyterm => '#attr_reader (Module)
')
Rubyterm.create(:rubyterm => '#attr_writer (Module)
')
Rubyterm.create(:rubyterm => '#autoclose= (IO)
')
Rubyterm.create(:rubyterm => '#autoclose? (IO)
')
Rubyterm.create(:rubyterm => '#autoload (Kernel)
')
Rubyterm.create(:rubyterm => '#autoload (Module)
')
Rubyterm.create(:rubyterm => '#autoload? (Kernel)
')
Rubyterm.create(:rubyterm => '#autoload? (Module)
')
Rubyterm.create(:rubyterm => '#backtrace (Exception)
')
Rubyterm.create(:rubyterm => '#backtrace (Thread)
')
Rubyterm.create(:rubyterm => '#begin (MatchData)
')
Rubyterm.create(:rubyterm => '#begin (Range)
')
Rubyterm.create(:rubyterm => '#between? (Comparable)
')
Rubyterm.create(:rubyterm => '#bind (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#binding (Kernel)
')
Rubyterm.create(:rubyterm => '#binding (Proc)
')
Rubyterm.create(:rubyterm => '#binmode (ARGF)
')
Rubyterm.create(:rubyterm => '#binmode (IO)
')
Rubyterm.create(:rubyterm => '#binmode? (ARGF)
')
Rubyterm.create(:rubyterm => '#binmode? (IO)
')
Rubyterm.create(:rubyterm => '#blksize (File::Stat)
')
Rubyterm.create(:rubyterm => '#block_given? (Kernel)
')
Rubyterm.create(:rubyterm => '#blockdev? (File::Stat)
')
Rubyterm.create(:rubyterm => '#blockdev? (FileTest)
')
Rubyterm.create(:rubyterm => '#blocks (File::Stat)
')
Rubyterm.create(:rubyterm => '#bytes (ARGF)
')
Rubyterm.create(:rubyterm => '#bytes (IO)
')
Rubyterm.create(:rubyterm => '#bytes (Random)
')
Rubyterm.create(:rubyterm => '#bytes (String)
')
Rubyterm.create(:rubyterm => '#bytesize (String)
')
Rubyterm.create(:rubyterm => '#byteslice (String)
')
Rubyterm.create(:rubyterm => '#call (Continuation)
')
Rubyterm.create(:rubyterm => '#call (Method)
')
Rubyterm.create(:rubyterm => '#call (Proc)
')
Rubyterm.create(:rubyterm => '#callcc (Kernel)
')
Rubyterm.create(:rubyterm => '#caller (Kernel)
')
Rubyterm.create(:rubyterm => '#capitalize (String)
')
Rubyterm.create(:rubyterm => '#capitalize (Symbol)
')
Rubyterm.create(:rubyterm => '#capitalize! (String)
')
Rubyterm.create(:rubyterm => '#captures (MatchData)
')
Rubyterm.create(:rubyterm => '#casecmp (String)
')
Rubyterm.create(:rubyterm => '#casecmp (Symbol)
')
Rubyterm.create(:rubyterm => '#casefold? (Regexp)
')
Rubyterm.create(:rubyterm => '#catch (Kernel)
')
Rubyterm.create(:rubyterm => '#ceil (Float)
')
Rubyterm.create(:rubyterm => '#ceil (Integer)
')
Rubyterm.create(:rubyterm => '#ceil (Numeric)
')
Rubyterm.create(:rubyterm => '#ceil (Rational)
')
Rubyterm.create(:rubyterm => '#center (String)
')
Rubyterm.create(:rubyterm => '#chardev? (File::Stat)
')
Rubyterm.create(:rubyterm => '#chardev? (FileTest)
')
Rubyterm.create(:rubyterm => '#chars (ARGF)
')
Rubyterm.create(:rubyterm => '#chars (IO)
')
Rubyterm.create(:rubyterm => '#chars (String)
')
Rubyterm.create(:rubyterm => '#chmod (File)
')
Rubyterm.create(:rubyterm => '#chomp (Kernel)
')
Rubyterm.create(:rubyterm => '#chomp (String)
')
Rubyterm.create(:rubyterm => '#chomp! (String)
')
Rubyterm.create(:rubyterm => '#chop (Kernel)
')
Rubyterm.create(:rubyterm => '#chop (String)
')
Rubyterm.create(:rubyterm => '#chop! (String)
')
Rubyterm.create(:rubyterm => '#chown (File)
')
Rubyterm.create(:rubyterm => '#chr (Integer)
')
Rubyterm.create(:rubyterm => '#chr (String)
')
Rubyterm.create(:rubyterm => '#chunk (Enumerable)
')
Rubyterm.create(:rubyterm => '#class (Object)
')
Rubyterm.create(:rubyterm => '#class_eval (Module)
')
Rubyterm.create(:rubyterm => '#class_exec (Module)
')
Rubyterm.create(:rubyterm => '#class_variable_defined? (Module)
')
Rubyterm.create(:rubyterm => '#class_variable_get (Module)
')
Rubyterm.create(:rubyterm => '#class_variable_set (Module)
')
Rubyterm.create(:rubyterm => '#class_variables (Module)
')
Rubyterm.create(:rubyterm => '#clear (Array)
')
Rubyterm.create(:rubyterm => '#clear (Hash)
')
Rubyterm.create(:rubyterm => '#clear (String)
')
Rubyterm.create(:rubyterm => '#clone (Method)
')
Rubyterm.create(:rubyterm => '#clone (Object)
')
Rubyterm.create(:rubyterm => '#clone (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#close (ARGF)
')
Rubyterm.create(:rubyterm => '#close (Dir)
')
Rubyterm.create(:rubyterm => '#close (IO)
')
Rubyterm.create(:rubyterm => '#close_on_exec= (IO)
')
Rubyterm.create(:rubyterm => '#close_on_exec? (IO)
')
Rubyterm.create(:rubyterm => '#close_read (IO)
')
Rubyterm.create(:rubyterm => '#close_write (IO)
')
Rubyterm.create(:rubyterm => '#closed? (ARGF)
')
Rubyterm.create(:rubyterm => '#closed? (IO)
')
Rubyterm.create(:rubyterm => '#codepoints (ARGF)
')
Rubyterm.create(:rubyterm => '#codepoints (IO)
')
Rubyterm.create(:rubyterm => '#codepoints (String)
')
Rubyterm.create(:rubyterm => '#coerce (Bignum)
')
Rubyterm.create(:rubyterm => '#coerce (Float)
')
Rubyterm.create(:rubyterm => '#coerce (Numeric)
')
Rubyterm.create(:rubyterm => '#collect (Array)
')
Rubyterm.create(:rubyterm => '#collect (Enumerable)
')
Rubyterm.create(:rubyterm => '#collect! (Array)
')
Rubyterm.create(:rubyterm => '#collect_concat (Enumerable)
')
Rubyterm.create(:rubyterm => '#combination (Array)
')
Rubyterm.create(:rubyterm => '#compact (Array)
')
Rubyterm.create(:rubyterm => '#compact! (Array)
')
Rubyterm.create(:rubyterm => '#compare_by_identity (Hash)
')
Rubyterm.create(:rubyterm => '#compare_by_identity? (Hash)
')
Rubyterm.create(:rubyterm => '#concat (Array)
')
Rubyterm.create(:rubyterm => '#concat (String)
')
Rubyterm.create(:rubyterm => '#conj (Complex)
')
Rubyterm.create(:rubyterm => '#conj (Numeric)
')
Rubyterm.create(:rubyterm => '#conjugate (Complex)
')
Rubyterm.create(:rubyterm => '#conjugate (Numeric)
')
Rubyterm.create(:rubyterm => '#const_defined? (Module)
')
Rubyterm.create(:rubyterm => '#const_get (Module)
')
Rubyterm.create(:rubyterm => '#const_missing (Module)
')
Rubyterm.create(:rubyterm => '#const_set (Module)
')
Rubyterm.create(:rubyterm => '#constants (Module)
')
Rubyterm.create(:rubyterm => '#convert (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#convpath (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#coredump? (Process::Status)
')
Rubyterm.create(:rubyterm => '#count (Array)
')
Rubyterm.create(:rubyterm => '#count (Enumerable)
')
Rubyterm.create(:rubyterm => '#count (String)
')
Rubyterm.create(:rubyterm => '#cover? (Range)
')
Rubyterm.create(:rubyterm => '#crypt (String)
')
Rubyterm.create(:rubyterm => '#ctime (File)
')
Rubyterm.create(:rubyterm => '#ctime (File::Stat)
')
Rubyterm.create(:rubyterm => '#ctime (Time)
')
Rubyterm.create(:rubyterm => '#curry (Proc)
')
Rubyterm.create(:rubyterm => '#cycle (Array)
')
Rubyterm.create(:rubyterm => '#cycle (Enumerable)
')
Rubyterm.create(:rubyterm => '#day (Time)
')
Rubyterm.create(:rubyterm => '#default (Hash)
')
Rubyterm.create(:rubyterm => '#default= (Hash)
')
Rubyterm.create(:rubyterm => '#default_proc (Hash)
')
Rubyterm.create(:rubyterm => '#default_proc= (Hash)
')
Rubyterm.create(:rubyterm => '#define_method (Module)
')
Rubyterm.create(:rubyterm => '#define_singleton_method (Object)
')
Rubyterm.create(:rubyterm => '#delete (Array)
')
Rubyterm.create(:rubyterm => '#delete (Hash)
')
Rubyterm.create(:rubyterm => '#delete (String)
')
Rubyterm.create(:rubyterm => '#delete! (String)
')
Rubyterm.create(:rubyterm => '#delete_at (Array)
')
Rubyterm.create(:rubyterm => '#delete_if (Array)
')
Rubyterm.create(:rubyterm => '#delete_if (Hash)
')
Rubyterm.create(:rubyterm => '#denominator (Complex)
')
Rubyterm.create(:rubyterm => '#denominator (Float)
')
Rubyterm.create(:rubyterm => '#denominator (Integer)
')
Rubyterm.create(:rubyterm => '#denominator (Numeric)
')
Rubyterm.create(:rubyterm => '#denominator (Rational)
')
Rubyterm.create(:rubyterm => '#destination_encoding (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#destination_encoding (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#destination_encoding (Encoding::UndefinedConversionError)
')
Rubyterm.create(:rubyterm => '#destination_encoding_name (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#destination_encoding_name (Encoding::UndefinedConversionError)
')
Rubyterm.create(:rubyterm => '#detect (Enumerable)
')
Rubyterm.create(:rubyterm => '#dev (File::Stat)
')
Rubyterm.create(:rubyterm => '#dev_major (File::Stat)
')
Rubyterm.create(:rubyterm => '#dev_minor (File::Stat)
')
Rubyterm.create(:rubyterm => '#directory? (File::Stat)
')
Rubyterm.create(:rubyterm => '#directory? (FileTest)
')
Rubyterm.create(:rubyterm => '#disasm (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '#disassemble (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '#display (Object)
')
Rubyterm.create(:rubyterm => '#div (Bignum)
')
Rubyterm.create(:rubyterm => '#div (Fixnum)
')
Rubyterm.create(:rubyterm => '#div (Numeric)
')
Rubyterm.create(:rubyterm => '#divmod (Bignum)
')
Rubyterm.create(:rubyterm => '#divmod (Fixnum)
')
Rubyterm.create(:rubyterm => '#divmod (Float)
')
Rubyterm.create(:rubyterm => '#divmod (Numeric)
')
Rubyterm.create(:rubyterm => '#downcase (String)
')
Rubyterm.create(:rubyterm => '#downcase (Symbol)
')
Rubyterm.create(:rubyterm => '#downcase! (String)
')
Rubyterm.create(:rubyterm => '#downto (Integer)
')
Rubyterm.create(:rubyterm => '#drop (Array)
')
Rubyterm.create(:rubyterm => '#drop (Enumerable)
')
Rubyterm.create(:rubyterm => '#drop_while (Array)
')
Rubyterm.create(:rubyterm => '#drop_while (Enumerable)
')
Rubyterm.create(:rubyterm => '#dst? (Time)
')
Rubyterm.create(:rubyterm => '#dummy? (Encoding)
')
Rubyterm.create(:rubyterm => '#dump (String)
')
Rubyterm.create(:rubyterm => '#dup (Object)
')
Rubyterm.create(:rubyterm => '#each (ARGF)
')
Rubyterm.create(:rubyterm => '#each (Array)
')
Rubyterm.create(:rubyterm => '#each (Dir)
')
Rubyterm.create(:rubyterm => '#each (Enumerator)
')
Rubyterm.create(:rubyterm => '#each (Hash)
')
Rubyterm.create(:rubyterm => '#each (IO)
')
Rubyterm.create(:rubyterm => '#each (Range)
')
Rubyterm.create(:rubyterm => '#each (Struct)
')
Rubyterm.create(:rubyterm => '#each_byte (ARGF)
')
Rubyterm.create(:rubyterm => '#each_byte (IO)
')
Rubyterm.create(:rubyterm => '#each_byte (String)
')
Rubyterm.create(:rubyterm => '#each_char (ARGF)
')
Rubyterm.create(:rubyterm => '#each_char (IO)
')
Rubyterm.create(:rubyterm => '#each_char (String)
')
Rubyterm.create(:rubyterm => '#each_codepoint (ARGF)
')
Rubyterm.create(:rubyterm => '#each_codepoint (IO)
')
Rubyterm.create(:rubyterm => '#each_codepoint (String)
')
Rubyterm.create(:rubyterm => '#each_cons (Enumerable)
')
Rubyterm.create(:rubyterm => '#each_entry (Enumerable)
')
Rubyterm.create(:rubyterm => '#each_index (Array)
')
Rubyterm.create(:rubyterm => '#each_key (Hash)
')
Rubyterm.create(:rubyterm => '#each_line (ARGF)
')
Rubyterm.create(:rubyterm => '#each_line (IO)
')
Rubyterm.create(:rubyterm => '#each_line (String)
')
Rubyterm.create(:rubyterm => '#each_pair (Hash)
')
Rubyterm.create(:rubyterm => '#each_pair (Struct)
')
Rubyterm.create(:rubyterm => '#each_slice (Enumerable)
')
Rubyterm.create(:rubyterm => '#each_value (Hash)
')
Rubyterm.create(:rubyterm => '#each_with_index (Enumerable)
')
Rubyterm.create(:rubyterm => '#each_with_index (Enumerator)
')
Rubyterm.create(:rubyterm => '#each_with_object (Enumerable)
')
Rubyterm.create(:rubyterm => '#each_with_object (Enumerator)
')
Rubyterm.create(:rubyterm => '#empty? (Array)
')
Rubyterm.create(:rubyterm => '#empty? (Hash)
')
Rubyterm.create(:rubyterm => '#empty? (String)
')
Rubyterm.create(:rubyterm => '#empty? (Symbol)
')
Rubyterm.create(:rubyterm => '#enclose (ThreadGroup)
')
Rubyterm.create(:rubyterm => '#enclosed? (ThreadGroup)
')
Rubyterm.create(:rubyterm => '#encode (String)
')
Rubyterm.create(:rubyterm => '#encode! (String)
')
Rubyterm.create(:rubyterm => '#encoding (Regexp)
')
Rubyterm.create(:rubyterm => '#encoding (String)
')
Rubyterm.create(:rubyterm => '#encoding (Symbol)
')
Rubyterm.create(:rubyterm => '#end (MatchData)
')
Rubyterm.create(:rubyterm => '#end (Range)
')
Rubyterm.create(:rubyterm => '#end_with? (String)
')
Rubyterm.create(:rubyterm => '#entries (Enumerable)
')
Rubyterm.create(:rubyterm => '#enum_for (Object)
')
Rubyterm.create(:rubyterm => '#eof (ARGF)
')
Rubyterm.create(:rubyterm => '#eof (IO)
')
Rubyterm.create(:rubyterm => '#eof? (ARGF)
')
Rubyterm.create(:rubyterm => '#eof? (IO)
')
Rubyterm.create(:rubyterm => '#eql? (Array)
')
Rubyterm.create(:rubyterm => '#eql? (Bignum)
')
Rubyterm.create(:rubyterm => '#eql? (Float)
')
Rubyterm.create(:rubyterm => '#eql? (Hash)
')
Rubyterm.create(:rubyterm => '#eql? (MatchData)
')
Rubyterm.create(:rubyterm => '#eql? (Method)
')
Rubyterm.create(:rubyterm => '#eql? (Numeric)
')
Rubyterm.create(:rubyterm => '#eql? (Object)
')
Rubyterm.create(:rubyterm => '#eql? (Proc)
')
Rubyterm.create(:rubyterm => '#eql? (Range)
')
Rubyterm.create(:rubyterm => '#eql? (Regexp)
')
Rubyterm.create(:rubyterm => '#eql? (String)
')
Rubyterm.create(:rubyterm => '#eql? (Struct)
')
Rubyterm.create(:rubyterm => '#eql? (Time)
')
Rubyterm.create(:rubyterm => '#eql? (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#equal? (BasicObject)
')
Rubyterm.create(:rubyterm => '#errno (SystemCallError)
')
Rubyterm.create(:rubyterm => '#error_bytes (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#error_char (Encoding::UndefinedConversionError)
')
Rubyterm.create(:rubyterm => '#eval (Binding)
')
Rubyterm.create(:rubyterm => '#eval (Kernel)
')
Rubyterm.create(:rubyterm => '#eval (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '#even? (Bignum)
')
Rubyterm.create(:rubyterm => '#even? (Fixnum)
')
Rubyterm.create(:rubyterm => '#even? (Integer)
')
Rubyterm.create(:rubyterm => '#exception (Exception)
')
Rubyterm.create(:rubyterm => '#exclude_end? (Range)
')
Rubyterm.create(:rubyterm => '#exec (Kernel)
')
Rubyterm.create(:rubyterm => '#executable? (File::Stat)
')
Rubyterm.create(:rubyterm => '#executable? (FileTest)
')
Rubyterm.create(:rubyterm => '#executable_real? (File::Stat)
')
Rubyterm.create(:rubyterm => '#executable_real? (FileTest)
')
Rubyterm.create(:rubyterm => '#exist? (FileTest)
')
Rubyterm.create(:rubyterm => '#exists? (FileTest)
')
Rubyterm.create(:rubyterm => '#exit (Kernel)
')
Rubyterm.create(:rubyterm => '#exit (Thread)
')
Rubyterm.create(:rubyterm => '#exit! (Kernel)
')
Rubyterm.create(:rubyterm => '#exit_value (LocalJumpError)
')
Rubyterm.create(:rubyterm => '#exited? (Process::Status)
')
Rubyterm.create(:rubyterm => '#exitstatus (Process::Status)
')
Rubyterm.create(:rubyterm => '#extend (Object)
')
Rubyterm.create(:rubyterm => '#extend_object (Module)
')
Rubyterm.create(:rubyterm => '#extended (Module)
')
Rubyterm.create(:rubyterm => '#external_encoding (ARGF)
')
Rubyterm.create(:rubyterm => '#external_encoding (IO)
')
Rubyterm.create(:rubyterm => '#fail (Kernel)
')
Rubyterm.create(:rubyterm => '#fcntl (IO)
')
Rubyterm.create(:rubyterm => '#fdatasync (IO)
')
Rubyterm.create(:rubyterm => '#fdiv (Bignum)
')
Rubyterm.create(:rubyterm => '#fdiv (Complex)
')
Rubyterm.create(:rubyterm => '#fdiv (Fixnum)
')
Rubyterm.create(:rubyterm => '#fdiv (Float)
')
Rubyterm.create(:rubyterm => '#fdiv (Numeric)
')
Rubyterm.create(:rubyterm => '#fdiv (Rational)
')
Rubyterm.create(:rubyterm => '#feed (Enumerator)
')
Rubyterm.create(:rubyterm => '#fetch (Array)
')
Rubyterm.create(:rubyterm => '#fetch (Hash)
')
Rubyterm.create(:rubyterm => '#file (ARGF)
')
Rubyterm.create(:rubyterm => '#file? (File::Stat)
')
Rubyterm.create(:rubyterm => '#file? (FileTest)
')
Rubyterm.create(:rubyterm => '#filename (ARGF)
')
Rubyterm.create(:rubyterm => '#fileno (ARGF)
')
Rubyterm.create(:rubyterm => '#fileno (IO)
')
Rubyterm.create(:rubyterm => '#fill (Array)
')
Rubyterm.create(:rubyterm => '#find (Enumerable)
')
Rubyterm.create(:rubyterm => '#find_all (Enumerable)
')
Rubyterm.create(:rubyterm => '#find_index (Array)
')
Rubyterm.create(:rubyterm => '#find_index (Enumerable)
')
Rubyterm.create(:rubyterm => '#finish (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#finite? (Float)
')
Rubyterm.create(:rubyterm => '#first (Array)
')
Rubyterm.create(:rubyterm => '#first (Enumerable)
')
Rubyterm.create(:rubyterm => '#first (Range)
')
Rubyterm.create(:rubyterm => '#fixed_encoding? (Regexp)
')
Rubyterm.create(:rubyterm => '#flat_map (Enumerable)
')
Rubyterm.create(:rubyterm => '#flatten (Array)
')
Rubyterm.create(:rubyterm => '#flatten (Hash)
')
Rubyterm.create(:rubyterm => '#flatten! (Array)
')
Rubyterm.create(:rubyterm => '#flock (File)
')
Rubyterm.create(:rubyterm => '#floor (Float)
')
Rubyterm.create(:rubyterm => '#floor (Integer)
')
Rubyterm.create(:rubyterm => '#floor (Numeric)
')
Rubyterm.create(:rubyterm => '#floor (Rational)
')
Rubyterm.create(:rubyterm => '#flush (IO)
')
Rubyterm.create(:rubyterm => '#force_encoding (String)
')
Rubyterm.create(:rubyterm => '#fork (Kernel)
')
Rubyterm.create(:rubyterm => '#format (Kernel)
')
Rubyterm.create(:rubyterm => '#freeze (Module)
')
Rubyterm.create(:rubyterm => '#freeze (Object)
')
Rubyterm.create(:rubyterm => '#friday? (Time)
')
Rubyterm.create(:rubyterm => '#frozen? (Array)
')
Rubyterm.create(:rubyterm => '#frozen? (Object)
')
Rubyterm.create(:rubyterm => '#fsync (IO)
')
Rubyterm.create(:rubyterm => '#ftype (File::Stat)
')
Rubyterm.create(:rubyterm => '#garbage_collect (GC)
')
Rubyterm.create(:rubyterm => '#gcd (Integer)
')
Rubyterm.create(:rubyterm => '#gcdlcm (Integer)
')
Rubyterm.create(:rubyterm => '#getbyte (ARGF)
')
Rubyterm.create(:rubyterm => '#getbyte (IO)
')
Rubyterm.create(:rubyterm => '#getbyte (String)
')
Rubyterm.create(:rubyterm => '#getc (ARGF)
')
Rubyterm.create(:rubyterm => '#getc (IO)
')
Rubyterm.create(:rubyterm => '#getgm (Time)
')
Rubyterm.create(:rubyterm => '#getlocal (Time)
')
Rubyterm.create(:rubyterm => '#gets (ARGF)
')
Rubyterm.create(:rubyterm => '#gets (IO)
')
Rubyterm.create(:rubyterm => '#gets (Kernel)
')
Rubyterm.create(:rubyterm => '#getutc (Time)
')
Rubyterm.create(:rubyterm => '#gid (File::Stat)
')
Rubyterm.create(:rubyterm => '#global_variables (Kernel)
')
Rubyterm.create(:rubyterm => '#gmt? (Time)
')
Rubyterm.create(:rubyterm => '#gmt_offset (Time)
')
Rubyterm.create(:rubyterm => '#gmtime (Time)
')
Rubyterm.create(:rubyterm => '#gmtoff (Time)
')
Rubyterm.create(:rubyterm => '#grep (Enumerable)
')
Rubyterm.create(:rubyterm => '#group (Thread)
')
Rubyterm.create(:rubyterm => '#group_by (Enumerable)
')
Rubyterm.create(:rubyterm => '#grpowned? (File::Stat)
')
Rubyterm.create(:rubyterm => '#grpowned? (FileTest)
')
Rubyterm.create(:rubyterm => '#gsub (Kernel)
')
Rubyterm.create(:rubyterm => '#gsub (String)
')
Rubyterm.create(:rubyterm => '#gsub! (String)
')
Rubyterm.create(:rubyterm => '#has_key? (Hash)
')
Rubyterm.create(:rubyterm => '#has_value? (Hash)
')
Rubyterm.create(:rubyterm => '#hash (Array)
')
Rubyterm.create(:rubyterm => '#hash (Bignum)
')
Rubyterm.create(:rubyterm => '#hash (Float)
')
Rubyterm.create(:rubyterm => '#hash (Hash)
')
Rubyterm.create(:rubyterm => '#hash (MatchData)
')
Rubyterm.create(:rubyterm => '#hash (Method)
')
Rubyterm.create(:rubyterm => '#hash (Object)
')
Rubyterm.create(:rubyterm => '#hash (Proc)
')
Rubyterm.create(:rubyterm => '#hash (Range)
')
Rubyterm.create(:rubyterm => '#hash (Regexp)
')
Rubyterm.create(:rubyterm => '#hash (String)
')
Rubyterm.create(:rubyterm => '#hash (Struct)
')
Rubyterm.create(:rubyterm => '#hash (Time)
')
Rubyterm.create(:rubyterm => '#hash (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#hex (String)
')
Rubyterm.create(:rubyterm => '#hour (Time)
')
Rubyterm.create(:rubyterm => '#i (Numeric)
')
Rubyterm.create(:rubyterm => '#id2name (Symbol)
')
Rubyterm.create(:rubyterm => '#identical? (FileTest)
')
Rubyterm.create(:rubyterm => '#imag (Complex)
')
Rubyterm.create(:rubyterm => '#imag (Numeric)
')
Rubyterm.create(:rubyterm => '#imaginary (Complex)
')
Rubyterm.create(:rubyterm => '#imaginary (Numeric)
')
Rubyterm.create(:rubyterm => '#include (Module)
')
Rubyterm.create(:rubyterm => '#include? (Array)
')
Rubyterm.create(:rubyterm => '#include? (Enumerable)
')
Rubyterm.create(:rubyterm => '#include? (Hash)
')
Rubyterm.create(:rubyterm => '#include? (Module)
')
Rubyterm.create(:rubyterm => '#include? (Range)
')
Rubyterm.create(:rubyterm => '#include? (String)
')
Rubyterm.create(:rubyterm => '#included (Module)
')
Rubyterm.create(:rubyterm => '#included_modules (Module)
')
Rubyterm.create(:rubyterm => '#incomplete_input? (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#index (Array)
')
Rubyterm.create(:rubyterm => '#index (String)
')
Rubyterm.create(:rubyterm => '#infinite? (Float)
')
Rubyterm.create(:rubyterm => '#inherited (Class)
')
Rubyterm.create(:rubyterm => '#initialize_copy (Array)
')
Rubyterm.create(:rubyterm => '#initialize_copy (Hash)
')
Rubyterm.create(:rubyterm => '#initialize_copy (String)
')
Rubyterm.create(:rubyterm => '#inject (Enumerable)
')
Rubyterm.create(:rubyterm => '#ino (File::Stat)
')
Rubyterm.create(:rubyterm => '#inplace_mode (ARGF)
')
Rubyterm.create(:rubyterm => '#inplace_mode= (ARGF)
')
Rubyterm.create(:rubyterm => '#insert (Array)
')
Rubyterm.create(:rubyterm => '#insert (String)
')
Rubyterm.create(:rubyterm => '#insert_output (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#inspect (Array)
')
Rubyterm.create(:rubyterm => '#inspect (Complex)
')
Rubyterm.create(:rubyterm => '#inspect (Dir)
')
Rubyterm.create(:rubyterm => '#inspect (Encoding)
')
Rubyterm.create(:rubyterm => '#inspect (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#inspect (Enumerator)
')
Rubyterm.create(:rubyterm => '#inspect (Exception)
')
Rubyterm.create(:rubyterm => '#inspect (File::Stat)
')
Rubyterm.create(:rubyterm => '#inspect (Hash)
')
Rubyterm.create(:rubyterm => '#inspect (IO)
')
Rubyterm.create(:rubyterm => '#inspect (MatchData)
')
Rubyterm.create(:rubyterm => '#inspect (Method)
')
Rubyterm.create(:rubyterm => '#inspect (NilClass)
')
Rubyterm.create(:rubyterm => '#inspect (Object)
')
Rubyterm.create(:rubyterm => '#inspect (Process::Status)
')
Rubyterm.create(:rubyterm => '#inspect (Range)
')
Rubyterm.create(:rubyterm => '#inspect (Rational)
')
Rubyterm.create(:rubyterm => '#inspect (Regexp)
')
Rubyterm.create(:rubyterm => '#inspect (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '#inspect (String)
')
Rubyterm.create(:rubyterm => '#inspect (Struct)
')
Rubyterm.create(:rubyterm => '#inspect (Symbol)
')
Rubyterm.create(:rubyterm => '#inspect (Thread)
')
Rubyterm.create(:rubyterm => '#inspect (Time)
')
Rubyterm.create(:rubyterm => '#inspect (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#instance_eval (BasicObject)
')
Rubyterm.create(:rubyterm => '#instance_exec (BasicObject)
')
Rubyterm.create(:rubyterm => '#instance_method (Module)
')
Rubyterm.create(:rubyterm => '#instance_methods (Module)
')
Rubyterm.create(:rubyterm => '#instance_of? (Object)
')
Rubyterm.create(:rubyterm => '#instance_variable_defined? (Object)
')
Rubyterm.create(:rubyterm => '#instance_variable_get (Object)
')
Rubyterm.create(:rubyterm => '#instance_variable_set (Object)
')
Rubyterm.create(:rubyterm => '#instance_variables (Object)
')
Rubyterm.create(:rubyterm => '#integer? (Integer)
')
Rubyterm.create(:rubyterm => '#integer? (Numeric)
')
Rubyterm.create(:rubyterm => '#intern (String)
')
Rubyterm.create(:rubyterm => '#intern (Symbol)
')
Rubyterm.create(:rubyterm => '#internal_encoding (ARGF)
')
Rubyterm.create(:rubyterm => '#internal_encoding (IO)
')
Rubyterm.create(:rubyterm => '#invert (Hash)
')
Rubyterm.create(:rubyterm => '#ioctl (IO)
')
Rubyterm.create(:rubyterm => '#is_a? (Object)
')
Rubyterm.create(:rubyterm => '#isatty (IO)
')
Rubyterm.create(:rubyterm => '#isdst (Time)
')
Rubyterm.create(:rubyterm => '#iterator? (Kernel)
')
Rubyterm.create(:rubyterm => '#join (Array)
')
Rubyterm.create(:rubyterm => '#join (Thread)
')
Rubyterm.create(:rubyterm => '#keep_if (Array)
')
Rubyterm.create(:rubyterm => '#keep_if (Hash)
')
Rubyterm.create(:rubyterm => '#key (Hash)
')
Rubyterm.create(:rubyterm => '#key? (Hash)
')
Rubyterm.create(:rubyterm => '#key? (Thread)
')
Rubyterm.create(:rubyterm => '#keys (Hash)
')
Rubyterm.create(:rubyterm => '#keys (Thread)
')
Rubyterm.create(:rubyterm => '#kill (Thread)
')
Rubyterm.create(:rubyterm => '#kind_of? (Object)
')
Rubyterm.create(:rubyterm => '#lambda (Kernel)
')
Rubyterm.create(:rubyterm => '#lambda? (Proc)
')
Rubyterm.create(:rubyterm => '#last (Array)
')
Rubyterm.create(:rubyterm => '#last (Range)
')
Rubyterm.create(:rubyterm => '#last_error (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#lcm (Integer)
')
Rubyterm.create(:rubyterm => '#length (Array)
')
Rubyterm.create(:rubyterm => '#length (Hash)
')
Rubyterm.create(:rubyterm => '#length (MatchData)
')
Rubyterm.create(:rubyterm => '#length (String)
')
Rubyterm.create(:rubyterm => '#length (Struct)
')
Rubyterm.create(:rubyterm => '#length (Symbol)
')
Rubyterm.create(:rubyterm => '#lineno (ARGF)
')
Rubyterm.create(:rubyterm => '#lineno (IO)
')
Rubyterm.create(:rubyterm => '#lineno= (ARGF)
')
Rubyterm.create(:rubyterm => '#lineno= (IO)
')
Rubyterm.create(:rubyterm => '#lines (ARGF)
')
Rubyterm.create(:rubyterm => '#lines (IO)
')
Rubyterm.create(:rubyterm => '#lines (String)
')
Rubyterm.create(:rubyterm => '#list (ThreadGroup)
')
Rubyterm.create(:rubyterm => '#ljust (String)
')
Rubyterm.create(:rubyterm => '#load (Kernel)
')
Rubyterm.create(:rubyterm => '#local_variables (Kernel)
')
Rubyterm.create(:rubyterm => '#localtime (Time)
')
Rubyterm.create(:rubyterm => '#lock (Mutex)
')
Rubyterm.create(:rubyterm => '#locked? (Mutex)
')
Rubyterm.create(:rubyterm => '#loop (Kernel)
')
Rubyterm.create(:rubyterm => '#lstat (File)
')
Rubyterm.create(:rubyterm => '#lstrip (String)
')
Rubyterm.create(:rubyterm => '#lstrip! (String)
')
Rubyterm.create(:rubyterm => '#magnitude (Bignum)
')
Rubyterm.create(:rubyterm => '#magnitude (Complex)
')
Rubyterm.create(:rubyterm => '#magnitude (Fixnum)
')
Rubyterm.create(:rubyterm => '#magnitude (Float)
')
Rubyterm.create(:rubyterm => '#magnitude (Numeric)
')
Rubyterm.create(:rubyterm => '#map (Array)
')
Rubyterm.create(:rubyterm => '#map (Enumerable)
')
Rubyterm.create(:rubyterm => '#map! (Array)
')
Rubyterm.create(:rubyterm => '#marshal_dump (Time)
')
Rubyterm.create(:rubyterm => '#marshal_load (Time)
')
Rubyterm.create(:rubyterm => '#match (Regexp)
')
Rubyterm.create(:rubyterm => '#match (String)
')
Rubyterm.create(:rubyterm => '#match (Symbol)
')
Rubyterm.create(:rubyterm => '#max (Enumerable)
')
Rubyterm.create(:rubyterm => '#max (Range)
')
Rubyterm.create(:rubyterm => '#max_by (Enumerable)
')
Rubyterm.create(:rubyterm => '#mday (Time)
')
Rubyterm.create(:rubyterm => '#member? (Enumerable)
')
Rubyterm.create(:rubyterm => '#member? (Hash)
')
Rubyterm.create(:rubyterm => '#member? (Range)
')
Rubyterm.create(:rubyterm => '#members (Struct)
')
Rubyterm.create(:rubyterm => '#merge (Hash)
')
Rubyterm.create(:rubyterm => '#merge! (Hash)
')
Rubyterm.create(:rubyterm => '#message (Exception)
')
Rubyterm.create(:rubyterm => '#method (Object)
')
Rubyterm.create(:rubyterm => '#method_added (Module)
')
Rubyterm.create(:rubyterm => '#method_defined? (Module)
')
Rubyterm.create(:rubyterm => '#method_missing (BasicObject)
')
Rubyterm.create(:rubyterm => '#method_removed (Module)
')
Rubyterm.create(:rubyterm => '#method_undefined (Module)
')
Rubyterm.create(:rubyterm => '#methods (Object)
')
Rubyterm.create(:rubyterm => '#min (Enumerable)
')
Rubyterm.create(:rubyterm => '#min (Range)
')
Rubyterm.create(:rubyterm => '#min (Time)
')
Rubyterm.create(:rubyterm => '#min_by (Enumerable)
')
Rubyterm.create(:rubyterm => '#minmax (Enumerable)
')
Rubyterm.create(:rubyterm => '#minmax_by (Enumerable)
')
Rubyterm.create(:rubyterm => '#mode (File::Stat)
')
Rubyterm.create(:rubyterm => '#module_eval (Module)
')
Rubyterm.create(:rubyterm => '#module_exec (Module)
')
Rubyterm.create(:rubyterm => '#module_function (Module)
')
Rubyterm.create(:rubyterm => '#modulo (Bignum)
')
Rubyterm.create(:rubyterm => '#modulo (Fixnum)
')
Rubyterm.create(:rubyterm => '#modulo (Float)
')
Rubyterm.create(:rubyterm => '#modulo (Numeric)
')
Rubyterm.create(:rubyterm => '#mon (Time)
')
Rubyterm.create(:rubyterm => '#monday? (Time)
')
Rubyterm.create(:rubyterm => '#month (Time)
')
Rubyterm.create(:rubyterm => '#mtime (File)
')
Rubyterm.create(:rubyterm => '#mtime (File::Stat)
')
Rubyterm.create(:rubyterm => '#name (Encoding)
')
Rubyterm.create(:rubyterm => '#name (Method)
')
Rubyterm.create(:rubyterm => '#name (Module)
')
Rubyterm.create(:rubyterm => '#name (NameError)
')
Rubyterm.create(:rubyterm => '#name (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#named_captures (Regexp)
')
Rubyterm.create(:rubyterm => '#names (Encoding)
')
Rubyterm.create(:rubyterm => '#names (MatchData)
')
Rubyterm.create(:rubyterm => '#names (Regexp)
')
Rubyterm.create(:rubyterm => '#nan? (Float)
')
Rubyterm.create(:rubyterm => '#new (Class)
')
Rubyterm.create(:rubyterm => '#next (Enumerator)
')
Rubyterm.create(:rubyterm => '#next (Integer)
')
Rubyterm.create(:rubyterm => '#next (String)
')
Rubyterm.create(:rubyterm => '#next (Symbol)
')
Rubyterm.create(:rubyterm => '#next! (String)
')
Rubyterm.create(:rubyterm => '#next_values (Enumerator)
')
Rubyterm.create(:rubyterm => '#nil? (NilClass)
')
Rubyterm.create(:rubyterm => '#nil? (Object)
')
Rubyterm.create(:rubyterm => '#nlink (File::Stat)
')
Rubyterm.create(:rubyterm => '#none? (Enumerable)
')
Rubyterm.create(:rubyterm => '#nonzero? (Numeric)
')
Rubyterm.create(:rubyterm => '#nsec (Time)
')
Rubyterm.create(:rubyterm => '#numerator (Complex)
')
Rubyterm.create(:rubyterm => '#numerator (Float)
')
Rubyterm.create(:rubyterm => '#numerator (Integer)
')
Rubyterm.create(:rubyterm => '#numerator (Numeric)
')
Rubyterm.create(:rubyterm => '#numerator (Rational)
')
Rubyterm.create(:rubyterm => '#object_id (Object)
')
Rubyterm.create(:rubyterm => '#oct (String)
')
Rubyterm.create(:rubyterm => '#odd? (Bignum)
')
Rubyterm.create(:rubyterm => '#odd? (Fixnum)
')
Rubyterm.create(:rubyterm => '#odd? (Integer)
')
Rubyterm.create(:rubyterm => '#offset (MatchData)
')
Rubyterm.create(:rubyterm => '#one? (Enumerable)
')
Rubyterm.create(:rubyterm => '#open (Kernel)
')
Rubyterm.create(:rubyterm => '#options (Regexp)
')
Rubyterm.create(:rubyterm => '#ord (Integer)
')
Rubyterm.create(:rubyterm => '#ord (String)
')
Rubyterm.create(:rubyterm => '#owned? (File::Stat)
')
Rubyterm.create(:rubyterm => '#owned? (FileTest)
')
Rubyterm.create(:rubyterm => '#owner (Method)
')
Rubyterm.create(:rubyterm => '#owner (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#p (Kernel)
')
Rubyterm.create(:rubyterm => '#pack (Array)
')
Rubyterm.create(:rubyterm => '#parameters (Method)
')
Rubyterm.create(:rubyterm => '#parameters (Proc)
')
Rubyterm.create(:rubyterm => '#parameters (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#partition (Enumerable)
')
Rubyterm.create(:rubyterm => '#partition (String)
')
Rubyterm.create(:rubyterm => '#path (ARGF)
')
Rubyterm.create(:rubyterm => '#path (Dir)
')
Rubyterm.create(:rubyterm => '#path (File)
')
Rubyterm.create(:rubyterm => '#peek (Enumerator)
')
Rubyterm.create(:rubyterm => '#peek_values (Enumerator)
')
Rubyterm.create(:rubyterm => '#permutation (Array)
')
Rubyterm.create(:rubyterm => '#phase (Complex)
')
Rubyterm.create(:rubyterm => '#phase (Float)
')
Rubyterm.create(:rubyterm => '#phase (Numeric)
')
Rubyterm.create(:rubyterm => '#pid (IO)
')
Rubyterm.create(:rubyterm => '#pid (Process::Status)
')
Rubyterm.create(:rubyterm => '#pipe? (File::Stat)
')
Rubyterm.create(:rubyterm => '#pipe? (FileTest)
')
Rubyterm.create(:rubyterm => '#polar (Complex)
')
Rubyterm.create(:rubyterm => '#polar (Numeric)
')
Rubyterm.create(:rubyterm => '#pop (Array)
')
Rubyterm.create(:rubyterm => '#pos (ARGF)
')
Rubyterm.create(:rubyterm => '#pos (Dir)
')
Rubyterm.create(:rubyterm => '#pos (IO)
')
Rubyterm.create(:rubyterm => '#pos= (ARGF)
')
Rubyterm.create(:rubyterm => '#pos= (Dir)
')
Rubyterm.create(:rubyterm => '#pos= (IO)
')
Rubyterm.create(:rubyterm => '#post_match (MatchData)
')
Rubyterm.create(:rubyterm => '#pre_match (MatchData)
')
Rubyterm.create(:rubyterm => '#pred (Integer)
')
Rubyterm.create(:rubyterm => '#prepend (String)
')
Rubyterm.create(:rubyterm => '#primitive_convert (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#primitive_errinfo (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#print (ARGF)
')
Rubyterm.create(:rubyterm => '#print (IO)
')
Rubyterm.create(:rubyterm => '#print (Kernel)
')
Rubyterm.create(:rubyterm => '#printf (ARGF)
')
Rubyterm.create(:rubyterm => '#printf (IO)
')
Rubyterm.create(:rubyterm => '#printf (Kernel)
')
Rubyterm.create(:rubyterm => '#priority (Thread)
')
Rubyterm.create(:rubyterm => '#priority= (Thread)
')
Rubyterm.create(:rubyterm => '#private (Module)
')
Rubyterm.create(:rubyterm => '#private_class_method (Module)
')
Rubyterm.create(:rubyterm => '#private_constant (Module)
')
Rubyterm.create(:rubyterm => '#private_instance_methods (Module)
')
Rubyterm.create(:rubyterm => '#private_method_defined? (Module)
')
Rubyterm.create(:rubyterm => '#private_methods (Object)
')
Rubyterm.create(:rubyterm => '#proc (Kernel)
')
Rubyterm.create(:rubyterm => '#product (Array)
')
Rubyterm.create(:rubyterm => '#protected (Module)
')
Rubyterm.create(:rubyterm => '#protected_instance_methods (Module)
')
Rubyterm.create(:rubyterm => '#protected_method_defined? (Module)
')
Rubyterm.create(:rubyterm => '#protected_methods (Object)
')
Rubyterm.create(:rubyterm => '#public (Module)
')
Rubyterm.create(:rubyterm => '#public_class_method (Module)
')
Rubyterm.create(:rubyterm => '#public_constant (Module)
')
Rubyterm.create(:rubyterm => '#public_instance_method (Module)
')
Rubyterm.create(:rubyterm => '#public_instance_methods (Module)
')
Rubyterm.create(:rubyterm => '#public_method (Object)
')
Rubyterm.create(:rubyterm => '#public_method_defined? (Module)
')
Rubyterm.create(:rubyterm => '#public_methods (Object)
')
Rubyterm.create(:rubyterm => '#public_send (Object)
')
Rubyterm.create(:rubyterm => '#push (Array)
')
Rubyterm.create(:rubyterm => '#putback (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#putc (ARGF)
')
Rubyterm.create(:rubyterm => '#putc (IO)
')
Rubyterm.create(:rubyterm => '#putc (Kernel)
')
Rubyterm.create(:rubyterm => '#puts (ARGF)
')
Rubyterm.create(:rubyterm => '#puts (IO)
')
Rubyterm.create(:rubyterm => '#puts (Kernel)
')
Rubyterm.create(:rubyterm => '#quo (Complex)
')
Rubyterm.create(:rubyterm => '#quo (Float)
')
Rubyterm.create(:rubyterm => '#quo (Numeric)
')
Rubyterm.create(:rubyterm => '#quo (Rational)
')
Rubyterm.create(:rubyterm => '#raise (Kernel)
')
Rubyterm.create(:rubyterm => '#raise (Thread)
')
Rubyterm.create(:rubyterm => '#rand (Kernel)
')
Rubyterm.create(:rubyterm => '#rand (Random)
')
Rubyterm.create(:rubyterm => '#rassoc (Array)
')
Rubyterm.create(:rubyterm => '#rassoc (Hash)
')
Rubyterm.create(:rubyterm => '#rationalize (Complex)
')
Rubyterm.create(:rubyterm => '#rationalize (Float)
')
Rubyterm.create(:rubyterm => '#rationalize (Integer)
')
Rubyterm.create(:rubyterm => '#rationalize (NilClass)
')
Rubyterm.create(:rubyterm => '#rationalize (Rational)
')
Rubyterm.create(:rubyterm => '#rdev (File::Stat)
')
Rubyterm.create(:rubyterm => '#rdev_major (File::Stat)
')
Rubyterm.create(:rubyterm => '#rdev_minor (File::Stat)
')
Rubyterm.create(:rubyterm => '#read (ARGF)
')
Rubyterm.create(:rubyterm => '#read (Dir)
')
Rubyterm.create(:rubyterm => '#read (IO)
')
Rubyterm.create(:rubyterm => '#read_nonblock (ARGF)
')
Rubyterm.create(:rubyterm => '#read_nonblock (IO)
')
Rubyterm.create(:rubyterm => '#readable? (File::Stat)
')
Rubyterm.create(:rubyterm => '#readable? (FileTest)
')
Rubyterm.create(:rubyterm => '#readable_real? (File::Stat)
')
Rubyterm.create(:rubyterm => '#readable_real? (FileTest)
')
Rubyterm.create(:rubyterm => '#readagain_bytes (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#readbyte (ARGF)
')
Rubyterm.create(:rubyterm => '#readbyte (IO)
')
Rubyterm.create(:rubyterm => '#readchar (ARGF)
')
Rubyterm.create(:rubyterm => '#readchar (IO)
')
Rubyterm.create(:rubyterm => '#readline (ARGF)
')
Rubyterm.create(:rubyterm => '#readline (IO)
')
Rubyterm.create(:rubyterm => '#readline (Kernel)
')
Rubyterm.create(:rubyterm => '#readlines (ARGF)
')
Rubyterm.create(:rubyterm => '#readlines (IO)
')
Rubyterm.create(:rubyterm => '#readlines (Kernel)
')
Rubyterm.create(:rubyterm => '#readpartial (ARGF)
')
Rubyterm.create(:rubyterm => '#readpartial (IO)
')
Rubyterm.create(:rubyterm => '#real (Complex)
')
Rubyterm.create(:rubyterm => '#real (Numeric)
')
Rubyterm.create(:rubyterm => '#real? (Complex)
')
Rubyterm.create(:rubyterm => '#real? (Numeric)
')
Rubyterm.create(:rubyterm => '#reason (LocalJumpError)
')
Rubyterm.create(:rubyterm => '#receiver (Method)
')
Rubyterm.create(:rubyterm => '#rect (Complex)
')
Rubyterm.create(:rubyterm => '#rect (Numeric)
')
Rubyterm.create(:rubyterm => '#rectangular (Complex)
')
Rubyterm.create(:rubyterm => '#rectangular (Numeric)
')
Rubyterm.create(:rubyterm => '#reduce (Enumerable)
')
Rubyterm.create(:rubyterm => '#regexp (MatchData)
')
Rubyterm.create(:rubyterm => '#rehash (Hash)
')
Rubyterm.create(:rubyterm => '#reject (Array)
')
Rubyterm.create(:rubyterm => '#reject (Enumerable)
')
Rubyterm.create(:rubyterm => '#reject (Hash)
')
Rubyterm.create(:rubyterm => '#reject! (Array)
')
Rubyterm.create(:rubyterm => '#reject! (Hash)
')
Rubyterm.create(:rubyterm => '#remainder (Bignum)
')
Rubyterm.create(:rubyterm => '#remainder (Numeric)
')
Rubyterm.create(:rubyterm => '#remove_class_variable (Module)
')
Rubyterm.create(:rubyterm => '#remove_const (Module)
')
Rubyterm.create(:rubyterm => '#remove_instance_variable (Object)
')
Rubyterm.create(:rubyterm => '#remove_method (Module)
')
Rubyterm.create(:rubyterm => '#reopen (IO)
')
Rubyterm.create(:rubyterm => '#repeated_combination (Array)
')
Rubyterm.create(:rubyterm => '#repeated_permutation (Array)
')
Rubyterm.create(:rubyterm => '#replace (Array)
')
Rubyterm.create(:rubyterm => '#replace (Hash)
')
Rubyterm.create(:rubyterm => '#replace (String)
')
Rubyterm.create(:rubyterm => '#replacement (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#replacement= (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#replicate (Encoding)
')
Rubyterm.create(:rubyterm => '#require (Kernel)
')
Rubyterm.create(:rubyterm => '#require_relative (Kernel)
')
Rubyterm.create(:rubyterm => '#respond_to? (Object)
')
Rubyterm.create(:rubyterm => '#respond_to_missing? (Object)
')
Rubyterm.create(:rubyterm => '#result (StopIteration)
')
Rubyterm.create(:rubyterm => '#resume (Fiber)
')
Rubyterm.create(:rubyterm => '#reverse (Array)
')
Rubyterm.create(:rubyterm => '#reverse (String)
')
Rubyterm.create(:rubyterm => '#reverse! (Array)
')
Rubyterm.create(:rubyterm => '#reverse! (String)
')
Rubyterm.create(:rubyterm => '#reverse_each (Array)
')
Rubyterm.create(:rubyterm => '#reverse_each (Enumerable)
')
Rubyterm.create(:rubyterm => '#rewind (ARGF)
')
Rubyterm.create(:rubyterm => '#rewind (Dir)
')
Rubyterm.create(:rubyterm => '#rewind (Enumerator)
')
Rubyterm.create(:rubyterm => '#rewind (IO)
')
Rubyterm.create(:rubyterm => '#rindex (Array)
')
Rubyterm.create(:rubyterm => '#rindex (String)
')
Rubyterm.create(:rubyterm => '#rjust (String)
')
Rubyterm.create(:rubyterm => '#rotate (Array)
')
Rubyterm.create(:rubyterm => '#rotate! (Array)
')
Rubyterm.create(:rubyterm => '#round (Float)
')
Rubyterm.create(:rubyterm => '#round (Integer)
')
Rubyterm.create(:rubyterm => '#round (Numeric)
')
Rubyterm.create(:rubyterm => '#round (Rational)
')
Rubyterm.create(:rubyterm => '#round (Time)
')
Rubyterm.create(:rubyterm => '#rpartition (String)
')
Rubyterm.create(:rubyterm => '#rstrip (String)
')
Rubyterm.create(:rubyterm => '#rstrip! (String)
')
Rubyterm.create(:rubyterm => '#run (Thread)
')
Rubyterm.create(:rubyterm => '#safe_level (Thread)
')
Rubyterm.create(:rubyterm => '#sample (Array)
')
Rubyterm.create(:rubyterm => '#saturday? (Time)
')
Rubyterm.create(:rubyterm => '#scan (String)
')
Rubyterm.create(:rubyterm => '#sec (Time)
')
Rubyterm.create(:rubyterm => '#seed (Random)
')
Rubyterm.create(:rubyterm => '#seek (ARGF)
')
Rubyterm.create(:rubyterm => '#seek (Dir)
')
Rubyterm.create(:rubyterm => '#seek (IO)
')
Rubyterm.create(:rubyterm => '#select (Array)
')
Rubyterm.create(:rubyterm => '#select (Enumerable)
')
Rubyterm.create(:rubyterm => '#select (Hash)
')
Rubyterm.create(:rubyterm => '#select (Kernel)
')
Rubyterm.create(:rubyterm => '#select (Struct)
')
Rubyterm.create(:rubyterm => '#select! (Array)
')
Rubyterm.create(:rubyterm => '#select! (Hash)
')
Rubyterm.create(:rubyterm => '#send (Object)
')
Rubyterm.create(:rubyterm => '#set_backtrace (Exception)
')
Rubyterm.create(:rubyterm => '#set_encoding (ARGF)
')
Rubyterm.create(:rubyterm => '#set_encoding (IO)
')
Rubyterm.create(:rubyterm => '#set_trace_func (Kernel)
')
Rubyterm.create(:rubyterm => '#set_trace_func (Thread)
')
Rubyterm.create(:rubyterm => '#setbyte (String)
')
Rubyterm.create(:rubyterm => '#setgid? (File::Stat)
')
Rubyterm.create(:rubyterm => '#setgid? (FileTest)
')
Rubyterm.create(:rubyterm => '#setuid? (File::Stat)
')
Rubyterm.create(:rubyterm => '#setuid? (FileTest)
')
Rubyterm.create(:rubyterm => '#shift (Array)
')
Rubyterm.create(:rubyterm => '#shift (Hash)
')
Rubyterm.create(:rubyterm => '#shuffle (Array)
')
Rubyterm.create(:rubyterm => '#shuffle! (Array)
')
Rubyterm.create(:rubyterm => '#signaled? (Process::Status)
')
Rubyterm.create(:rubyterm => '#signo (SignalException)
')
Rubyterm.create(:rubyterm => '#singleton_class (Object)
')
Rubyterm.create(:rubyterm => '#singleton_method_added (BasicObject)
')
Rubyterm.create(:rubyterm => '#singleton_method_added (Numeric)
')
Rubyterm.create(:rubyterm => '#singleton_method_removed (BasicObject)
')
Rubyterm.create(:rubyterm => '#singleton_method_undefined (BasicObject)
')
Rubyterm.create(:rubyterm => '#singleton_methods (Object)
')
Rubyterm.create(:rubyterm => '#size (Array)
')
Rubyterm.create(:rubyterm => '#size (Bignum)
')
Rubyterm.create(:rubyterm => '#size (File)
')
Rubyterm.create(:rubyterm => '#size (File::Stat)
')
Rubyterm.create(:rubyterm => '#size (FileTest)
')
Rubyterm.create(:rubyterm => '#size (Fixnum)
')
Rubyterm.create(:rubyterm => '#size (Hash)
')
Rubyterm.create(:rubyterm => '#size (MatchData)
')
Rubyterm.create(:rubyterm => '#size (String)
')
Rubyterm.create(:rubyterm => '#size (Struct)
')
Rubyterm.create(:rubyterm => '#size (Symbol)
')
Rubyterm.create(:rubyterm => '#size? (File::Stat)
')
Rubyterm.create(:rubyterm => '#size? (FileTest)
')
Rubyterm.create(:rubyterm => '#skip (ARGF)
')
Rubyterm.create(:rubyterm => '#sleep (Kernel)
')
Rubyterm.create(:rubyterm => '#sleep (Mutex)
')
Rubyterm.create(:rubyterm => '#slice (Array)
')
Rubyterm.create(:rubyterm => '#slice (String)
')
Rubyterm.create(:rubyterm => '#slice (Symbol)
')
Rubyterm.create(:rubyterm => '#slice! (Array)
')
Rubyterm.create(:rubyterm => '#slice! (String)
')
Rubyterm.create(:rubyterm => '#slice_before (Enumerable)
')
Rubyterm.create(:rubyterm => '#socket? (File::Stat)
')
Rubyterm.create(:rubyterm => '#socket? (FileTest)
')
Rubyterm.create(:rubyterm => '#sort (Array)
')
Rubyterm.create(:rubyterm => '#sort (Enumerable)
')
Rubyterm.create(:rubyterm => '#sort! (Array)
')
Rubyterm.create(:rubyterm => '#sort_by (Enumerable)
')
Rubyterm.create(:rubyterm => '#sort_by! (Array)
')
Rubyterm.create(:rubyterm => '#source (Regexp)
')
Rubyterm.create(:rubyterm => '#source_encoding (Encoding::Converter)
')
Rubyterm.create(:rubyterm => '#source_encoding (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#source_encoding (Encoding::UndefinedConversionError)
')
Rubyterm.create(:rubyterm => '#source_encoding_name (Encoding::InvalidByteSequenceError)
')
Rubyterm.create(:rubyterm => '#source_encoding_name (Encoding::UndefinedConversionError)
')
Rubyterm.create(:rubyterm => '#source_location (Method)
')
Rubyterm.create(:rubyterm => '#source_location (Proc)
')
Rubyterm.create(:rubyterm => '#source_location (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#spawn (Kernel)
')
Rubyterm.create(:rubyterm => '#split (String)
')
Rubyterm.create(:rubyterm => '#sprintf (Kernel)
')
Rubyterm.create(:rubyterm => '#squeeze (String)
')
Rubyterm.create(:rubyterm => '#squeeze! (String)
')
Rubyterm.create(:rubyterm => '#srand (Kernel)
')
Rubyterm.create(:rubyterm => '#start_with? (String)
')
Rubyterm.create(:rubyterm => '#stat (IO)
')
Rubyterm.create(:rubyterm => '#status (SystemExit)
')
Rubyterm.create(:rubyterm => '#status (Thread)
')
Rubyterm.create(:rubyterm => '#step (Numeric)
')
Rubyterm.create(:rubyterm => '#step (Range)
')
Rubyterm.create(:rubyterm => '#sticky? (File::Stat)
')
Rubyterm.create(:rubyterm => '#sticky? (FileTest)
')
Rubyterm.create(:rubyterm => '#stop? (Thread)
')
Rubyterm.create(:rubyterm => '#stopped? (Process::Status)
')
Rubyterm.create(:rubyterm => '#stopsig (Process::Status)
')
Rubyterm.create(:rubyterm => '#store (Hash)
')
Rubyterm.create(:rubyterm => '#strftime (Time)
')
Rubyterm.create(:rubyterm => '#string (MatchData)
')
Rubyterm.create(:rubyterm => '#strip (String)
')
Rubyterm.create(:rubyterm => '#strip! (String)
')
Rubyterm.create(:rubyterm => '#sub (Kernel)
')
Rubyterm.create(:rubyterm => '#sub (String)
')
Rubyterm.create(:rubyterm => '#sub! (String)
')
Rubyterm.create(:rubyterm => '#subsec (Time)
')
Rubyterm.create(:rubyterm => '#succ (Fixnum)
')
Rubyterm.create(:rubyterm => '#succ (Integer)
')
Rubyterm.create(:rubyterm => '#succ (String)
')
Rubyterm.create(:rubyterm => '#succ (Symbol)
')
Rubyterm.create(:rubyterm => '#succ (Time)
')
Rubyterm.create(:rubyterm => '#succ! (String)
')
Rubyterm.create(:rubyterm => '#success? (Process::Status)
')
Rubyterm.create(:rubyterm => '#success? (SystemExit)
')
Rubyterm.create(:rubyterm => '#sum (String)
')
Rubyterm.create(:rubyterm => '#sunday? (Time)
')
Rubyterm.create(:rubyterm => '#superclass (Class)
')
Rubyterm.create(:rubyterm => '#swapcase (String)
')
Rubyterm.create(:rubyterm => '#swapcase (Symbol)
')
Rubyterm.create(:rubyterm => '#swapcase! (String)
')
Rubyterm.create(:rubyterm => '#symlink? (File::Stat)
')
Rubyterm.create(:rubyterm => '#symlink? (FileTest)
')
Rubyterm.create(:rubyterm => '#sync (IO)
')
Rubyterm.create(:rubyterm => '#sync= (IO)
')
Rubyterm.create(:rubyterm => '#synchronize (Mutex)
')
Rubyterm.create(:rubyterm => '#syscall (Kernel)
')
Rubyterm.create(:rubyterm => '#sysread (IO)
')
Rubyterm.create(:rubyterm => '#sysseek (IO)
')
Rubyterm.create(:rubyterm => '#system (Kernel)
')
Rubyterm.create(:rubyterm => '#syswrite (IO)
')
Rubyterm.create(:rubyterm => '#taint (Object)
')
Rubyterm.create(:rubyterm => '#tainted? (Object)
')
Rubyterm.create(:rubyterm => '#take (Array)
')
Rubyterm.create(:rubyterm => '#take (Enumerable)
')
Rubyterm.create(:rubyterm => '#take_while (Array)
')
Rubyterm.create(:rubyterm => '#take_while (Enumerable)
')
Rubyterm.create(:rubyterm => '#tap (Object)
')
Rubyterm.create(:rubyterm => '#tell (ARGF)
')
Rubyterm.create(:rubyterm => '#tell (Dir)
')
Rubyterm.create(:rubyterm => '#tell (IO)
')
Rubyterm.create(:rubyterm => '#terminate (Thread)
')
Rubyterm.create(:rubyterm => '#termsig (Process::Status)
')
Rubyterm.create(:rubyterm => '#test (Kernel)
')
Rubyterm.create(:rubyterm => '#throw (Kernel)
')
Rubyterm.create(:rubyterm => '#thursday? (Time)
')
Rubyterm.create(:rubyterm => '#times (Integer)
')
Rubyterm.create(:rubyterm => '#to_a (ARGF)
')
Rubyterm.create(:rubyterm => '#to_a (Array)
')
Rubyterm.create(:rubyterm => '#to_a (Enumerable)
')
Rubyterm.create(:rubyterm => '#to_a (Hash)
')
Rubyterm.create(:rubyterm => '#to_a (MatchData)
')
Rubyterm.create(:rubyterm => '#to_a (NilClass)
')
Rubyterm.create(:rubyterm => '#to_a (RubyVM::InstructionSequence)
')
Rubyterm.create(:rubyterm => '#to_a (Struct)
')
Rubyterm.create(:rubyterm => '#to_a (Time)
')
Rubyterm.create(:rubyterm => '#to_ary (Array)
')
Rubyterm.create(:rubyterm => '#to_c (NilClass)
')
Rubyterm.create(:rubyterm => '#to_c (Numeric)
')
Rubyterm.create(:rubyterm => '#to_c (String)
')
Rubyterm.create(:rubyterm => '#to_enum (Object)
')
Rubyterm.create(:rubyterm => '#to_f (Bignum)
')
Rubyterm.create(:rubyterm => '#to_f (Complex)
')
Rubyterm.create(:rubyterm => '#to_f (Fixnum)
')
Rubyterm.create(:rubyterm => '#to_f (Float)
')
Rubyterm.create(:rubyterm => '#to_f (NilClass)
')
Rubyterm.create(:rubyterm => '#to_f (Rational)
')
Rubyterm.create(:rubyterm => '#to_f (String)
')
Rubyterm.create(:rubyterm => '#to_f (Time)
')
Rubyterm.create(:rubyterm => '#to_hash (Hash)
')
Rubyterm.create(:rubyterm => '#to_i (ARGF)
')
Rubyterm.create(:rubyterm => '#to_i (Complex)
')
Rubyterm.create(:rubyterm => '#to_i (Float)
')
Rubyterm.create(:rubyterm => '#to_i (IO)
')
Rubyterm.create(:rubyterm => '#to_i (Integer)
')
Rubyterm.create(:rubyterm => '#to_i (NilClass)
')
Rubyterm.create(:rubyterm => '#to_i (Process::Status)
')
Rubyterm.create(:rubyterm => '#to_i (Rational)
')
Rubyterm.create(:rubyterm => '#to_i (String)
')
Rubyterm.create(:rubyterm => '#to_i (Time)
')
Rubyterm.create(:rubyterm => '#to_int (Float)
')
Rubyterm.create(:rubyterm => '#to_int (Integer)
')
Rubyterm.create(:rubyterm => '#to_int (Numeric)
')
Rubyterm.create(:rubyterm => '#to_io (ARGF)
')
Rubyterm.create(:rubyterm => '#to_io (IO)
')
Rubyterm.create(:rubyterm => '#to_path (Dir)
')
Rubyterm.create(:rubyterm => '#to_path (File)
')
Rubyterm.create(:rubyterm => '#to_proc (Method)
')
Rubyterm.create(:rubyterm => '#to_proc (Proc)
')
Rubyterm.create(:rubyterm => '#to_proc (Symbol)
')
Rubyterm.create(:rubyterm => '#to_r (Complex)
')
Rubyterm.create(:rubyterm => '#to_r (Float)
')
Rubyterm.create(:rubyterm => '#to_r (Integer)
')
Rubyterm.create(:rubyterm => '#to_r (NilClass)
')
Rubyterm.create(:rubyterm => '#to_r (Rational)
')
Rubyterm.create(:rubyterm => '#to_r (String)
')
Rubyterm.create(:rubyterm => '#to_r (Time)
')
Rubyterm.create(:rubyterm => '#to_s (ARGF)
')
Rubyterm.create(:rubyterm => '#to_s (Array)
')
Rubyterm.create(:rubyterm => '#to_s (Bignum)
')
Rubyterm.create(:rubyterm => '#to_s (Complex)
')
Rubyterm.create(:rubyterm => '#to_s (Encoding)
')
Rubyterm.create(:rubyterm => '#to_s (Exception)
')
Rubyterm.create(:rubyterm => '#to_s (FalseClass)
')
Rubyterm.create(:rubyterm => '#to_s (Fixnum)
')
Rubyterm.create(:rubyterm => '#to_s (Float)
')
Rubyterm.create(:rubyterm => '#to_s (Hash)
')
Rubyterm.create(:rubyterm => '#to_s (MatchData)
')
Rubyterm.create(:rubyterm => '#to_s (Method)
')
Rubyterm.create(:rubyterm => '#to_s (Module)
')
Rubyterm.create(:rubyterm => '#to_s (NameError)
')
Rubyterm.create(:rubyterm => '#to_s (NilClass)
')
Rubyterm.create(:rubyterm => '#to_s (Object)
')
Rubyterm.create(:rubyterm => '#to_s (Proc)
')
Rubyterm.create(:rubyterm => '#to_s (Process::Status)
')
Rubyterm.create(:rubyterm => '#to_s (Range)
')
Rubyterm.create(:rubyterm => '#to_s (Rational)
')
Rubyterm.create(:rubyterm => '#to_s (Regexp)
')
Rubyterm.create(:rubyterm => '#to_s (String)
')
Rubyterm.create(:rubyterm => '#to_s (Struct)
')
Rubyterm.create(:rubyterm => '#to_s (Symbol)
')
Rubyterm.create(:rubyterm => '#to_s (Time)
')
Rubyterm.create(:rubyterm => '#to_s (TrueClass)
')
Rubyterm.create(:rubyterm => '#to_s (UnboundMethod)
')
Rubyterm.create(:rubyterm => '#to_str (String)
')
Rubyterm.create(:rubyterm => '#to_sym (String)
')
Rubyterm.create(:rubyterm => '#to_sym (Symbol)
')
Rubyterm.create(:rubyterm => '#to_write_io (ARGF)
')
Rubyterm.create(:rubyterm => '#tr (String)
')
Rubyterm.create(:rubyterm => '#tr! (String)
')
Rubyterm.create(:rubyterm => '#tr_s (String)
')
Rubyterm.create(:rubyterm => '#tr_s! (String)
')
Rubyterm.create(:rubyterm => '#trace_var (Kernel)
')
Rubyterm.create(:rubyterm => '#transfer (Fiber)
')
Rubyterm.create(:rubyterm => '#transpose (Array)
')
Rubyterm.create(:rubyterm => '#trap (Kernel)
')
Rubyterm.create(:rubyterm => '#truncate (File)
')
Rubyterm.create(:rubyterm => '#truncate (Float)
')
Rubyterm.create(:rubyterm => '#truncate (Integer)
')
Rubyterm.create(:rubyterm => '#truncate (Numeric)
')
Rubyterm.create(:rubyterm => '#truncate (Rational)
')
Rubyterm.create(:rubyterm => '#trust (Object)
')
Rubyterm.create(:rubyterm => '#try_lock (Mutex)
')
Rubyterm.create(:rubyterm => '#tty? (IO)
')
Rubyterm.create(:rubyterm => '#tuesday? (Time)
')
Rubyterm.create(:rubyterm => '#tv_nsec (Time)
')
Rubyterm.create(:rubyterm => '#tv_sec (Time)
')
Rubyterm.create(:rubyterm => '#tv_usec (Time)
')
Rubyterm.create(:rubyterm => '#uid (File::Stat)
')
Rubyterm.create(:rubyterm => '#unbind (Method)
')
Rubyterm.create(:rubyterm => '#undef_method (Module)
')
Rubyterm.create(:rubyterm => '#ungetbyte (IO)
')
Rubyterm.create(:rubyterm => '#ungetc (IO)
')
Rubyterm.create(:rubyterm => '#uniq (Array)
')
Rubyterm.create(:rubyterm => '#uniq! (Array)
')
Rubyterm.create(:rubyterm => '#unlock (Mutex)
')
Rubyterm.create(:rubyterm => '#unpack (String)
')
Rubyterm.create(:rubyterm => '#unshift (Array)
')
Rubyterm.create(:rubyterm => '#untaint (Object)
')
Rubyterm.create(:rubyterm => '#untrace_var (Kernel)
')
Rubyterm.create(:rubyterm => '#untrust (Object)
')
Rubyterm.create(:rubyterm => '#untrusted? (Object)
')
Rubyterm.create(:rubyterm => '#upcase (String)
')
Rubyterm.create(:rubyterm => '#upcase (Symbol)
')
Rubyterm.create(:rubyterm => '#upcase! (String)
')
Rubyterm.create(:rubyterm => '#update (Hash)
')
Rubyterm.create(:rubyterm => '#upto (Integer)
')
Rubyterm.create(:rubyterm => '#upto (String)
')
Rubyterm.create(:rubyterm => '#usec (Time)
')
Rubyterm.create(:rubyterm => '#utc (Time)
')
Rubyterm.create(:rubyterm => '#utc? (Time)
')
Rubyterm.create(:rubyterm => '#utc_offset (Time)
')
Rubyterm.create(:rubyterm => '#valid_encoding? (String)
')
Rubyterm.create(:rubyterm => '#value (Thread)
')
Rubyterm.create(:rubyterm => '#value? (Hash)
')
Rubyterm.create(:rubyterm => '#values (Hash)
')
Rubyterm.create(:rubyterm => '#values (Struct)
')
Rubyterm.create(:rubyterm => '#values_at (Array)
')
Rubyterm.create(:rubyterm => '#values_at (Hash)
')
Rubyterm.create(:rubyterm => '#values_at (MatchData)
')
Rubyterm.create(:rubyterm => '#values_at (Struct)
')
Rubyterm.create(:rubyterm => '#wakeup (Thread)
')
Rubyterm.create(:rubyterm => '#warn (Kernel)
')
Rubyterm.create(:rubyterm => '#wday (Time)
')
Rubyterm.create(:rubyterm => '#wednesday? (Time)
')
Rubyterm.create(:rubyterm => '#with_index (Enumerator)
')
Rubyterm.create(:rubyterm => '#with_object (Enumerator)
')
Rubyterm.create(:rubyterm => '#world_readable? (File::Stat)
')
Rubyterm.create(:rubyterm => '#world_readable? (FileTest)
')
Rubyterm.create(:rubyterm => '#world_writable? (File::Stat)
')
Rubyterm.create(:rubyterm => '#world_writable? (FileTest)
')
Rubyterm.create(:rubyterm => '#writable? (File::Stat)
')
Rubyterm.create(:rubyterm => '#writable? (FileTest)
')
Rubyterm.create(:rubyterm => '#writable_real? (File::Stat)
')
Rubyterm.create(:rubyterm => '#writable_real? (FileTest)
')
Rubyterm.create(:rubyterm => '#write (ARGF)
')
Rubyterm.create(:rubyterm => '#write (IO)
')
Rubyterm.create(:rubyterm => '#write_nonblock (IO)
')
Rubyterm.create(:rubyterm => '#yday (Time)
')
Rubyterm.create(:rubyterm => '#year (Time)
')
Rubyterm.create(:rubyterm => '#yield (Proc)
')
Rubyterm.create(:rubyterm => '#zero? (File::Stat)
')
Rubyterm.create(:rubyterm => '#zero? (FileTest)
')
Rubyterm.create(:rubyterm => '#zero? (Fixnum)
')
Rubyterm.create(:rubyterm => '#zero? (Float)
')
Rubyterm.create(:rubyterm => '#zero? (Numeric)
')
Rubyterm.create(:rubyterm => '#zip (Array)
')
Rubyterm.create(:rubyterm => '#zip (Enumerable)
')
Rubyterm.create(:rubyterm => '#zone (Time)
')
Rubyterm.create(:rubyterm => '#| (Array)
')
Rubyterm.create(:rubyterm => '#| (Bignum)
')
Rubyterm.create(:rubyterm => '#| (FalseClass)
')
Rubyterm.create(:rubyterm => '#| (Fixnum)
')
Rubyterm.create(:rubyterm => '#| (NilClass)
')
Rubyterm.create(:rubyterm => '#| (TrueClass)
')
Rubyterm.create(:rubyterm => '#~ (Bignum)
')
Rubyterm.create(:rubyterm => '#~ (Complex)
')
Rubyterm.create(:rubyterm => '#~ (Fixnum)
')
Rubyterm.create(:rubyterm => '#~ (Regexp)
')
